### ISSUE TITLE
Add HS Physics to the Carnival Theme (80% Completion Goal)

### ISSUE THREAD

**Issue by openstaxalina** [openstax/cnx-recipes#1696]
@openstaxalina commented on [Tue Mar 07 2017](https://github.com/openstax/oer.exports/issues/2579)

# Link to content

https://content04.cnx.org/contents/IKZFuFtg

# Folder with screenshots of elements in current PDF (uses _University Physics_ designs)

https://drive.google.com/drive/folders/1ZfToqyardXiMLnFNNr7zTYxijSGPeqX2

# Design elements in the title

General things:
- [x] Teacher Content/Support (these have a class (`class="os-teacher"`) - use a display="none")
- [x] Section Key Terms

### [Carnival asset folder for icons.](https://drive.google.com/drive/folders/1zA3DPstc7Cx1BqtdMYCEB_NGXn1D0XXw)
Feature-like things:
- [x] Grasp Check - New condensed boxed note please see #1706 for thorough notes.  
- [x] Snap Lab - BOXED NOTE - B7 #0074BC - `class="snap-lab"` [Link to SnapLab cell on Theme Sheet](https://docs.google.com/spreadsheets/d/1vW0EHvn8fZgvTxZIm9xQXsqsnIDcolqwt5rWKtx4JEY/edit#gid=1663003137&range=A194)
- [x] Worked Example - ICONNED NOTE - R3 #C31427  - `class="worked-example"`- It will use the same icon and specs as the [Examples](https://docs.google.com/spreadsheets/d/1vW0EHvn8fZgvTxZIm9xQXsqsnIDcolqwt5rWKtx4JEY/edit#gid=1663003137&range=A243) but these are coded as a note with the class `worked-example` - should I update the spec sheet with a icon note version of this?
- [x] Tips for Success  - New condensed boxed note please see #1705 for thorough notes.  
- [x] Work in Physics - ICONNED NOTE - BR2 #B05E36 - `class="work-in-physics"` - It will use the carnival-career icon.
- [x] Fun in Physics - ICONNED NOTE - R4 #B10069 - `class="fun-in-physics"` - It will use the carnival-funphysics icon. 
- [x] Boundless Physics - ICONNED NOTE - G7 #1E9575 - `class="boundless-physics"`
- [x] Links to Physics - ICONNED NOTE - G3 #84AE52 - `class="links-to-physics"` - It will use carnival-linktolearning.svg icon. - note: NOT a condensed icon note. Let me know if you need a different SVG. 
- [x] Watch Physics - ICONNED NOTE - B7 #0074BC - `class="watch-physics"` It will use carnival-visualconnection.svg icon
- [x] Virtual Physics - BOXED NOTE - G7 #1E9575 `class="virtual-physics os-interactive"`

In-Section Exercises
- [x] Practice Problems

End of Section Exercises
- [x] Check Your Understanding (use from other Carnival books?)

Collating Elements (EOC):
- [x] Section Summaries (needs restyling; use from other Carnival books?)
- [x] Concept Items
- [x] Critical Thinking
- [x] Problems
- [x] Performance Task
- [x] Test Prep Multiple Choice
- [x] Test Prep Short Answer
- [x] Test Prep Extended Response

# HS Physics Tagging Legend
https://drive.google.com/a/rice.edu/file/d/0B7KX2mPxBBE9X0dyc3RKRUlpeTg/view?usp=sharing

**Comment by brittweinstein** [comment]
@wilkus27 most of these components have been built out in other books and can be reused, however there are a couple of new issues linked in the list above.

**Comment by wilkus27** [comment]
**Note**: can be closed if issues:
- https://github.com/openstax/cnx-recipes/issues/1839
- https://github.com/openstax/cnx-recipes/issues/1848
- https://github.com/openstax/cnx-recipes/issues/1854
- https://github.com/openstax/cnx-recipes/issues/1833
pass the tests.

**Comment by MartaSztuka** [comment]
Listed issues passed the test.
