### ISSUE TITLE
EOC Issues

### ISSUE THREAD

**Issue by brittweinstein** [openstax/cnx-recipes#2015]
Main card (#1942) - might want to delete it and replace with this.

- [x]  Remove all the list components, move them to a lists components file, add to shapes. 
**Note**: suggestion on new naming scheme. 
`block`
`block__element`
`block--modifier` 
for example:
`list`
`list__margin`
`list_margin--left`
See https://csswizardry.com/2013/01/mindbemding-getting-your-head-round-bem-syntax/ ~~(we can discuss this before implementing)~~ Decision: we will experiment with the naming scheme and re-evaluate in a couple sprints.

- [x]  Remove all titles functions, move them to one component (done, I think), add to shapes. #2039
- [x]  Add a title + image component to handle #1983 and #1978
note: do we need a title components file that can be reused in all shapes? yes, see #2043

- [x]  Remove the named table components and add existing table components to shapes in EOC (this includes exercises etc.) #2040

- [x]   Remove the EOC specific figure components, use the existing figure components, add to shapes #2041

- [x]  Move exercises out of EOC to their own components file, include EOC specific exercises to EOC and everywhere else, make sure all exercises are handled in the appropriate shapes for other parts, use optional where applicable to avoid repetition. - #1870 

- [x]  remove `Multiple_Choice` component and replace with generic component or unique settings if necessary  #2042

- [x]  **Rework exercises columns to display better (`display: table` seems to be wrecking havok): #1956 (high priority)**

- Handle un-clustered EOC sections (probably with two shapes: one `section-separated`, one `unclustered-section` or something) - #2013

**Comment by wilkus27** [comment]
@helenemccarron I like this idea:

![image](https://user-images.githubusercontent.com/40228854/76204747-46280400-61f9-11ea-8b30-afc17b8b0f82.png)

I think that then we can remove all files related with `chapter` and `module` which contain just titles. I mean those files: https://github.com/openstax/cnx-recipes/blob/master/styles/designs/carnival/parts/_chapter-components.scss and https://github.com/openstax/cnx-recipes/blob/master/styles/designs/carnival/parts/_module-components.scss and of course related with them `-shapes.scss` and `-settings.scss`.

**Comment by brittany-johnson** [comment]
All issues in this epic have been completed, closing.
