### ISSUE TITLE
Add Prealgebra 2e, Intermediate Algebra 2e & Elementary Algebra 2e (dev math) to the corn theme (80%)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2059]
# Link to content
- [Prealgebra 2e](https://katalyst01.cnx.org/contents/8PqQvvyo@6.2:BqV5n3Yt@4/Introduction)

# General Notes 
![image](https://user-images.githubusercontent.com/11299125/78192415-b6fbbe00-743d-11ea-8051-655473a91ba9.png)

- Books share very similar content, almost over lapping
- Referred to as the Developmental Math trio
- Will be VERY close to the existing PDF design

# Design elements in the title
Since this is the first title, there will be a lot more work with this title than others.

## General things:
- [x] Splash image (#1752 - theme wide)
- [x] Folio (#2143 - theme wide)
- [x] Titles and headers (#2144)
- [x] Figure & table caption styling (#2185) 
- [x] Chapter Outline (#2189)
- [x] Learning Objectives (#2190)
- [x] Basic table (includes `class="column-header"` tables as well since design is very similar) (#2204)
- [x] unnumbered unstyled tables (#2205) 

## Book parts
- [x] Table of Contents (#2060 - theme wide)
- [x] Preface (#2320) 
- [x] Appendix (#2320) - same as preface but with a box to show numbering
- [x] Introduction Page (#2314)
- [x] Index (https://github.com/openstax/cnx-recipes/issues/2428)

#### Collating Elements (EOC)
- [x] Chapter Review contains the following:
- [x] Key Terms - (#2321 - theme wide)
- [x] Key Concepts - Broken up by sections (#2322) 
The next two are on the same level as the Chapter Review
- [x] Review Exercises - Please see detailed specifications here (#2164)
- [x] Practice Test - see above..should be the same as (#2164) 

## Feature-like things:
- [x] Be Prepared Exercises - condensed icon with no title note - Numbering schema 1.1, 1.2, 1.3... resets every chapter; Answers in answer key collate to its own section - `class <note class=”be-prepared”>`  (#2179)
- [ ] Tokens and token lists (#2186)
- [x] No Class Notes (#2191) 
- [x] Manipulative Mathematics feature (`<note class="manipulative-math">`) Icon Boxed Note (#2200) 
- [x] How To feature (`class="howto"`) Icon Boxed Note with title (#2208) 
- [x] Links to Literacy (`class="links-to-literacy"`) Icon boxed note (#2200 ) icon is [here](https://drive.google.com/open?id=1l6RLBG_UHGrCY6G5EYaFfbSQDCsd7K2V)
- [x] Examples with no titles (#2203)
- [x] Try Its - condensed icon with no title note - Numbering schema 1.1, 1.2, 1.3... resets every chapter; Answers in answer key collate to its own section - class `<note class="try">` [Icon link](https://drive.google.com/open?id=1d5-2oB2rBjRZGEF98_w47v6Fnh5xgC75) (#2179) 
- [x] Media (`class="media"`) - condensed icon with title note (#2206) 

## In-Section Exercises
- [x] There is a section at the end of each module (3.4 Exercises) that requires an icon next to the header [icon](https://drive.google.com/open?id=1rDSdtv96AqFHv5oZiusFqsD0c7BEWXGP) - structure is similar to (#2164) `class="section-exercises"`

## EOB
Appendix, Index  and Answer key should follow same header schema set above
- [x] Three columns turned on for answer key with title and header 

# Tagging Legend
https://docs.google.com/spreadsheets/d/1dLK6qOU4y-2E1odgBJLQYLwZU2FUBcqbpFBD2gH6Wec/edit#gid=0

**Comment by wilkus27** [comment]
List of tasks In Progress
--------
When element is applied to all three books it can be marked as done in list from above.

- [ ] Table of Contents Prealgebra (https://github.com/openstax/cnx-recipes/issues/2316)
- [ ] Module titles Prealgebra (https://github.com/openstax/cnx-recipes/issues/2328)
- [ ] Preface Prealgebra (https://github.com/openstax/cnx-recipes/issues/2327)
- [ ] Learning Objectives Prealgebra (https://github.com/openstax/cnx-recipes/issues/2383)
- [ ] Be Prepared note Prealgebra (https://github.com/openstax/cnx-recipes/issues/2386)
- [ ] Manipulative Math note Prealgebra (https://github.com/openstax/cnx-recipes/issues/2390)
- [ ] no class note Prealgebra (https://github.com/openstax/cnx-recipes/issues/2393)
- [ ] How To note Prealgebra (https://github.com/openstax/cnx-recipes/issues/2395)
