### ISSUE TITLE
Add College Algebra with coreq (priority), Precalculus and Algebra & Trigonometry to the Corn Theme (80%)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2207]
# Link to content
The co-req content is IN the College Algebra collection in chapter 1 & 2.
- [College Algebra](https://katalyst01.cnx.org/contents/9b08c294-057f-4201-9f48-5d6ad992740d)
- [Precalculus](https://katalyst01.cnx.org/contents/fd53eae1-fa23-47c7-bb1b-972349835c3c)
- [Algebra & Trigonometry](https://katalyst01.cnx.org/contents/13ac107a-f15f-49d2-97e8-60ab2e3b519c)

# General Notes 
![image](https://user-images.githubusercontent.com/11299125/78192415-b6fbbe00-743d-11ea-8051-655473a91ba9.png)

- All 3 books share very similar content and definitely overlaps
- Lifting design from developmental math with a few changes
- This will be using the PRECALCULUS recipe and numbering scheme (numbering goes 1, 2, 3, etc and resets every section); learning objectives go 1.1, 1.2, 1.3, etc

# Design elements in the title

I will note which one is the same as developmental math (#2059 )

## General things:
- [x] Table of Contents - same as dev math
- [x] Splash image - same as dev math
- [x] Folio - same as dev math
- [x] Titles and headers - same as dev math
- [x] Figure & table caption styling - same as dev math
- [x] Chapter Outline - same as dev math
- [x] Learning Objectives - same as dev math
- [x] Table designs - same as dev math
- [x] **NEW** Footnotes (https://github.com/openstax/cnx-recipes/issues/2465)

## Feature-like things:

- [x] Tokens and token lists - same as dev math
- [x] No Class Notes - same as dev math
- [x] Equation (#2447) 
- [x] **NEW** Examples with title (#2209) 
- [x] How To - same as dev math design but targeted with class `class="how-to-notitle"`
- [x] Try Its - same as dev math (#2179) 
- [x] **NEW** Q&A - similar to math condensed icon with no title but with this [icon](https://drive.google.com/open?id=1siu8lGy50uNOsog48D95U9RFCH2n2U_G)  (#2200)
- [x]  Media (`class="media-notitle"`) - same as dev math condensed icon with title note (#2206) 
- [x] **NEW** Coreq section (#2222) 

## Collating Elements (EOC):
- [x] Key Equations
- [x] Key Concepts
- [x] Review Exercises - Same specs as dev math as seen in #2164 
- [x] Practice Test 

## In-Section Exercises
- [x] There is a section at the end of each module (3.4 Exercises) - function should be the same as in dev math

## EOB
Appendix, Index and Answer key should follow same header schema set above
- [x] Three columns turned on for answer key with title and header 

# Tagging Legend
https://docs.google.com/spreadsheets/d/1dLK6qOU4y-2E1odgBJLQYLwZU2FUBcqbpFBD2gH6Wec/edit#gid=0

**Comment by ajluk** [comment]
Hi @lwtchu could you create issue with specs as documentation for Key Equations? I have one question related to this: How shoud we devide Composite Chapters for these books in the EoC?:
Should it be similar as we did it on dev-math books: 

**Chapter review**
- Key Terms
- Key Equations
- Key Concepts

**Exercises**
- Review Exercises 
- Practice Test

And I guess the Practice Test exercises here should also use the specs from dev-math-exercises (#2164)? Just asking to be sure.

**Comment by wilkus27** [comment]
@lwtchu We also noticed footnotes in College Algebra Coreq. How should we style them?

**Comment by lwtchu** [comment]
@wilkus27 here's the card for footnotes, i added it to the checklist: https://github.com/openstax/cnx-recipes/issues/2465

**Comment by lwtchu** [comment]
@ajluk What you have listed there is good. Thanks!
