### ISSUE TITLE
Add Precalculus, College Algebra, Algebra & Trigonometry to the Corn Theme (80%)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2234]
# Link to content
Uses EXACT same content as #2207 but adjusting the recipe to suppress the `coreq-skills` material. 

- [Precalculus](https://katalyst01.cnx.org/contents/fd53eae1-fa23-47c7-bb1b-972349835c3c)
- [College Algebra](https://katalyst01.cnx.org/contents/9b08c294-057f-4201-9f48-5d6ad992740d)
- [Algebra & Trigonometry](https://katalyst01.cnx.org/contents/13ac107a-f15f-49d2-97e8-60ab2e3b519c)

# General Notes
- [ ] The design should be EXACTLY the same as #2207 
- [x] Uses the existing Precalculus recipe - EXACTLY the same recipe as #2207 
- [x] **NEW** Suppresses the `coreq-skills` class #2223 

# End result
We should have two baked styles/recipes that are identical except the Precalculus one suppresses the `coreq-skills` content. And the other coreq recipe does not suppress the `coreq-skills` content. 

# Tagging Legend
https://docs.google.com/spreadsheets/d/1dLK6qOU4y-2E1odgBJLQYLwZU2FUBcqbpFBD2gH6Wec/edit#gid=0

**Comment by wilkus27** [comment]
List of tasks In Progress
---------
