### ISSUE TITLE
Add Calculus to the Corn Theme (80%)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2241]
# Link to content
- [Volume 1](https://katalyst01.cnx.org/contents/8b89d172-2927-466f-8661-01abc7ccdba4)
- [Volume 2](https://katalyst01.cnx.org/contents/1d39a348-071f-4537-85b6-c98912458c3c)
- [Volume 3](https://katalyst01.cnx.org/contents/a31cd793-2162-4e9e-acb5-6e6bbd76a5fa)
# General Notes 
This book is mostly box feature heavy. We need to test some of the EOC content first before moving them into the 3 column format

# Design elements in the title

## General things:
- [x] Table of Contents 
- [x] Splash image
- [ ] Folio 
- [x] Titles and headers 
- [x] Figure & table caption styling
- [x] Chapter Outline 
- [x] Learning Objectives - instead of bullets, have numbering (#2557)
- [x] Table designs 

## Feature-like things:
- [x] no class notes
- [x] equation numbering (#2210) 
- [x] **NEW** theorem feature `class="theorem"` - numbered boxed note with class and title #2256 
- [x] **NEW** problem solving strategy feature `class="problem-solving"` - same design as #2256 but with no numbering. background is B4:   `#F7FAFB`; title color: B1:   `#093D4C`
- [x] examples
- [x] checkpoint `class="checkpoint"`- same structure as #2179 but does not need the "be prepared" title text - use the be prepared icon 
- [x] **NEW** student activity `class="project"` - #2266 
- [x] media note `class="media-2"` - #2206 

## Collating Elements (EOC):
Composite collation format:

```
Chapter # Review
> Key Terms
> Key Equations
> Key Concepts
> Review Exercises
```
- [x] Key Terms
- [x] Key Equations
- [x] Key Concepts
- [x] Chapter Review Exercises - currently NOT in 3 column, need to test

## In-Section Exercises
- [x] End of Section exercises  - currently NOT in three column. Need to test

## EOB
Appendix & answer keys...

# Tagging Legend
https://docs.google.com/spreadsheets/d/18d6BUgdmSLAyW-KrpJJNPbyEDFFtqZNkuahqgPTEILc/edit#gid=0

**Comment by wilkus27** [comment]
@lwtchu Should we create some composite chapters in EOC? Now all EOC modules are regular composite pages.

**Comment by lwtchu** [comment]
@wilkus27 can we leave those as is?

**Comment by wilkus27** [comment]
@lwtchu Yes, of course. But then there will be no `Chapter Review` title at the beggining. In PDF from production it appears:

![image](https://user-images.githubusercontent.com/40228854/88816635-e4befc80-d1bc-11ea-9b03-484c25e3e974.png)

**Comment by lwtchu** [comment]
@wilkus27 ooh i didn't realize. let me ..double check with a few people first

**Comment by lwtchu** [comment]
@wilkus27 can we do
Chapter # Review
> Key Terms
> Key Equations
> Key Concepts
> Review Exercises

if this seems ok i can update the list above

**Comment by wilkus27** [comment]
@lwtchu Thank you! It looks fine, I will change the structure in recipes.

**Comment by ajluk** [comment]
@lwtchu I have found out that there is also a Media note in the Calculus book: 
![image](https://user-images.githubusercontent.com/55203598/89032928-fa0b6680-d335-11ea-8f21-b511f172dca4.png)
Should it be styled with the same specs from here in this book as well: https://github.com/openstax/cnx-recipes/issues/2206?

**Comment by lwtchu** [comment]
@ajluk yes it should be. let me add it to the list. thanks for catching

**Comment by ajluk** [comment]
@lwtchu I have a question about Chapter Review Exercises , End of Section Exercises and Answer Key. In the previous books from corn theme they were in 3 columns

**Comment by ajluk** [comment]
@lwtchu I have also one more question about Footnotes in Calculus will there be any? I couldn't find one in Calculus vol1.

**Comment by lwtchu** [comment]
@ajluk there are no footnotes in calculus
