### ISSUE TITLE
Add Statistics to the Corn Theme (80%)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2267]
# Link to content
- [HS Statistics](https://katalyst01.cnx.org/contents/OUoRAf2P@7.1:FG5DHMVK@2/Introduction)
- [Introductory Statistics](https://katalyst01.cnx.org/contents/MBiUQmmY@24.3:2T34_25K@14/Introduction)
- [Business Statistics](https://katalyst01.cnx.org/contents/tWu56V64@36.3:-mZCQZc7@7/Introduction)
# General Notes 
These books share the SAME recipe and design.

# Design elements in the title

## General things:
- [x] Table of Contents 
- [x] Splash image
- [ ] Folio 
- [x] Titles and headers 
- [x] Figure & table caption styling
- [x] **NEW** Chapter Objectives - these are in the intro. there is no chapter outline and no learning objectives per module
- [x] Table designs 
- [x] This book has footnotes, please take care to test them at least once - styling should be the same as carnival theme but with the different font/font scale

## Feature-like things:
- [x] no class notes
- [x] collaborative exercise - `class="statistics collab"` - use #2200 - manipulative mathematics icon but rename title to collaborative exercise
- [x] **NEW** Stat Lab feature #2273 
- [x]  **KIND OF NEW** statistics try it `class="statistics try"` - use #2200 - but use the try it icon - we need this in a box because there are some very long try its. feature title can be next to the icon as `Try It #.#`
- [x] **KIND OF NEW** calculator feature `class="statistics calculator"` -  use #2200 structure but with different colors ( G1:  `#F4F7F4` for background, B2:   `#1E7E91` for the title text) use the [calculator icon](https://drive.google.com/open?id=1ZRGDpRPA7eoKet9rZi6WlcMSYgGTXct_)

## Collating Elements (EOC) + in section exercises:
- [x] Key Terms #2321 
- [x] Chapter Review #2615
- [x] Formula review #2614 
- [x] Practice #2612 
- [x] Bringing it together: practice #2612 
- [x] Homework #2612 
- [x] Bringing it together homework #2612 
- [x] References #2631
- [x] Solutions  #2632

## EOB
- [x] Appendix
- [x] Index

# Tagging Legend
https://drive.google.com/file/d/0B3JbYkOtM9PyVi1KeUFNdVFwNG8/view?ths=true

**Comment by wilkus27** [comment]
@lwtchu Structure of Introductory Statistics is very strange (I haven't checked two other books yet). This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/89299554-1aedf780-d667-11ea-9a31-1d78550c7805.png)

References and Solutions are in the EOC. There is no Answer Key and References at the end of the book.

Here are the modules from EOB:

![image](https://user-images.githubusercontent.com/40228854/89299679-4cff5980-d667-11ea-9b63-a7b4bbbd4837.png)

Is it all intentional?

**Comment by lwtchu** [comment]
@wilkus27 this is intentional. thank you for checking

**Comment by ajluk** [comment]
@lwtchu Should the footnotes be styled differently than from specs provided here for corn theme: https://github.com/openstax/cnx-recipes/issues/2465 ?

**Comment by lwtchu** [comment]
@ajluk it should not be styled differently, let's keep with #2465

**Comment by ajluk** [comment]
@lwtchu There also Examples present in the Statistics. I have linked the issue to this epic: https://github.com/openstax/cnx-recipes/issues/2601.

**Comment by ajluk** [comment]
@lwtchu Do we need to style `terms` in the corn theme as we did for the carnival theme?

**Comment by lwtchu** [comment]
@ajluk can you elaborate on the styling? like give it a bold treatment and if it has a `class="no-emphasis"` it has no bold? if so, yes -- the `<term>` tag is pretty universal in the library and should apply to all books/all themes

**Comment by wilkus27** [comment]
@lwtchu There is no card with specs for **References**. How we should style it in Corn Theme? Statistics is the first book from this theme with this module.

**Comment by wilkus27** [comment]
@lwtchu We need also card for **Solutions** module. As I said in one of the previous comment in Statistics there is no Answer Key, answers appear in EOC in Solutions module. This is how it looks now:

![image](https://user-images.githubusercontent.com/40228854/90231970-3e116780-de1c-11ea-9ae9-0d7c2859c407.png)

How we should style it?

**Comment by lwtchu** [comment]
@wilkus27 can the references be the same as the chapter review? the header schema (broken up by section) is the same and the text should just display as is with the base font; as for the solution i think what we're doing in the homework and practice should suffice - would you need separate cards or can i reference those documentation cards on the Statistics checklist?

**Comment by wilkus27** [comment]
@lwtchu so in References we shouldn't apply indents like in carnival theme?

Anatomy:
![image](https://user-images.githubusercontent.com/40228854/90395703-3c060d80-e095-11ea-814a-1cf4c895be22.png)


About your question, I think it would be better to create separate documentation cards for References and Solutions.

**Comment by lwtchu** [comment]
@wilkus27 here's the card for references #2631 and solutions #2632
