### ISSUE TITLE
Update documentation and create coding assessment in preparation for new hires

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#2640]
# What happened?

We'll soon be adding two new developers to our team. This card is to track documentation and assessment creation efforts. I will be updating with links to documentation that has been updated and a list of documentation that needs to be updated or created. 

**ToDo**
- [x] [Update COPS cli docs with install instructions ](https://github.com/openstax/output-producer-service/tree/master/bakery)
- [x] [Update cnx-recipes deployment docs](https://openstax.atlassian.net/wiki/spaces/CE/pages/506101774/cnx-recipes+release+process) 
- [x] [Update oer.exports deployment docs ](https://openstax.atlassian.net/wiki/spaces/CE/pages/506068993/oer.exports+release+process)
- [x] Review all applicants in HR portal
- [x] Conduct phone screenings w/ selected applicants
- [x] Create new coding assessment for canidates
- [x] Finalize interview questions
- [x] Call references, review assessments, send rejection emails 
- [x] update documentation of cnx-recipes repo and update styles tutorial and documentation
- [x] Finalize onboarding plan (credentials, laptops, meeting w/ other team members, etc)
