### ISSUE TITLE
Add Business Ethics (80%) to the cardboard theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2684]
# Link to content
-  **PLEASE USE BUSINESS ETHICS FOR ALL TESTING FOR NOW** Business Ethics: https://katalyst01.cnx.org/contents/914ac66e-e1ec-486d-8a9c-97b0f7a99774 / collection id on production: col25722
-  Business Law I: https://katalyst01.cnx.org/contents/464a3fba-68c1-426a-99f9-597e739dc911
-  Intellectual Property: https://content02.cnx.org/contents/Pkn7H67H@9.2:7W1n_aKP@5/Preface

# General Notes 

# Design elements in the title
Since this is the first title, there will be a lot more work with this title than others.

General things:
- [x] Table of Contents #1740
- [x] Splash image #2642 
- [x] Figure caption/title/number styling #2643 
- [x] Headers #2644 
- [x] Chapter Outline / Introduction #2655
- [x] Section number treatment #2710 
- [x] Learning Objectives #2711 
- [x] Tables #2741 (mostly default style, `top-titled`) 
- [x] Endnotes #2745 (not to be confused with footnotes (goes to footer of pate) or references (collate to end of book))
- [x] Footnotes #2747
- [x] Blockquotes #2749 
- [x] Lists https://github.com/openstax/cnx-recipes/issues/2712 

### [Cardboard asset folder for icons.](https://drive.google.com/drive/folders/1wsO8nLf7QJXj6YnB1pmjPle0hVYwMoyP)
Feature-like things:
- [x] Link to Learning (`<note class="link-to-learning">`) - uses #2737 
- [x] Cases from the Real World (`class="real-world"`) - uses #2737 with color option 2.
- [x] What Would You Do? (`class="what-would"`) - uses #2737 with color option 3
- [x] Ethics Across Time and Cultures (`class="ethics-across"`) - uses #2737 with color option 3

End of Chapter Content
- [x] Key Terms (`class="key-terms"`) #2742 
- [x] Summary (`class="section-summary"`) #2743
- [x] Assessment Questions (`class="assessment-questions"`) #2744 
- [x] Endnotes (see above)

End of Book Content
- [x] Appendices (they exists, follow header schema set from header issue referenced above)
- [x] Index #2746
- [x] Answer Key #2748 

# Tagging Legend
https://docs.google.com/spreadsheets/d/1wKOFlG1i59jzEx8FZSf38845XzraNXmCkYQOcb7JDtg/edit#gid=0

**Comment by ajluk** [comment]
Hi @lwtchu I'm creating basics files for cardboard today and couldn't find a color scheme issue for this theme. I have picked some colors from the issues you have created for Business Ethics but I guess not all of them are there. Could create one for us?
What colors I have already grabbed:
scheme: 
    B2:    #344456,
    B3:    #0DC0DC,
    B4:    #24739E,
    B5:    #D6D9DD,
    B6:    #D3E3EB,
    Grey1: #F9F9F9,
    Grey2: #F2F2F2,
    Grey3: #757474,
    black: #000000,
    white: #FFFFFF,

**Comment by ajluk** [comment]
@lwtchu I have also converted this issue to epic to make it possible for me to link it to my atom working issue, but I didn't set any points to it. I hope that is okay.

**Comment by andymuddimer** [comment]
Colors
P1: #3B2746
P2: #772949
P3: #9028A3
B2: #344456
B3: #0DC0DC
B4: #24739E
B5: #D6D9DD
B6: #D3E3EB
Y1: #E3A354
O1: #CB634E
O2: #D34D32
O3: #F37541
G1: #1E9575
G2: #F2F2F2
Grey1: #F9F9F9
Grey2: #757474
Grey3: #EAEAEA
black: #000000
white: #FFFFFF

Fonts
sansFont: ("Noto Sans", sans-serif)
eobTitleFont: ("IBM Plex Sans", sans-serif)
baseFont: "Noto Sans"
titleFont: "Dosis" (Astronomy) or "Roboto Condensed" for the rest
baseFontSize: 12px
baseLineHeight: 1.5rem

**Comment by ajluk** [comment]
@andymuddimer Thank you! I will update the PR.

**Comment by wilkus27** [comment]
@lwtchu Business Ethics is almost done. Is content of Business Law I and Intellectual Property ready to work on or we should start working on Introduction to Business?

**Comment by lwtchu** [comment]
@wilkus27 they use the same recipe - there's no additional content!

**Comment by lwtchu** [comment]
@meeragovindaraju this is ready for you to test. 

Please 
- [ ] Generate the pdf on COPS using the production ID for Business Ethics (col25722)
- [ ] Compare it with the existing PDF on openstax.org 
- [ ] Open any issues and assign to me please :) !

**Comment by meeragovindaraju** [comment]
Opened the following bug cards:
[EOC Endnotes numbered list not inline as it is in the old PDF]([https://github.com/openstax/cnx-recipes/issues/3045])

[Chapter 11 listed EOB Answer key](https://github.com/openstax/cnx-recipes/issues/3046)

[extra set of quotes and look different than in the old PDF](https://github.com/openstax/cnx-recipes/issues/3044)

[Summary and key terms are switched in order](https://github.com/openstax/cnx-recipes/issues/3043)

[Large page break](https://github.com/openstax/cnx-recipes/issues/3042)
