### ISSUE TITLE
Add College Success (80%) to Cardboard Theme 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2768]
# Link to content
-  

# General Notes 

# Design elements in the title
Since this is the first title, there will be a lot more work with this title than others.

General things:
- [ ] Table of Contents #1740
- [ ] Splash image #2642 
- [ ] Figure caption/title/number styling #2643 
- [ ] Headers #2644 
- [ ] Chapter Outline / Introduction #2655
- [ ] Section number treatment #2710 
- [ ] Learning Objectives #2711 
- [ ] Tables #2741 (mostly default style, `top-titled`) 
- [ ] Endnotes #2745 (not to be confused with footnotes (goes to footer of pate) or references (collate to end of book))
- [ ] Footnotes #2747
- [ ] Blockquotes #2749 

### [Cardboard asset folder for icons.](https://drive.google.com/drive/folders/1wsO8nLf7QJXj6YnB1pmjPle0hVYwMoyP)
Feature-like things:
- [ ] Link to Learning (`<note class="link-to-learning">`) - uses #2737 
- [ ] Cases from the Real World (`class="real-world"`) - uses #2737 with color option 2.
- [ ] What Would You Do? (`class="what-would"`) - uses #2737 with color option 3
- [ ] Ethics Across Time and Cultures (`class="ethics-across"`) - uses #2737 with color option 3

End of Chapter Content
- [ ] Key Terms (`class="key-terms"`) #2742 
- [ ] Summary (`class="section-summary"`) #2743
- [ ] Assessment Questions (`class="assessment-questions"`) #2744 
- [ ] Endnotes (see above)

End of Book Content
- [ ] Appendices (they exists, follow header schema set from header issue referenced above)
- [ ] Index #2746
- [ ] Answer Key #2748 

# Tagging Legend
