### ISSUE TITLE
(!WIP!) Add Introduction to Business (80%) to the Cardboard Theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2775]
# Link to content
-  https://katalyst01.cnx.org/contents/6GaKFJp9@7.1:YmYE9otg@4/Introduction

# General Notes 

# Design elements in the title

General things:
- [ ] Table of Contents #1740 - uses the blue version
- [ ] Splash image #2642  - splash intro icon is the campus icon: https://drive.google.com/file/d/1M7YKIHVgQY5BAdaalZPK6IP5ausLFxjj/view?usp=sharing
- [ ] Figure caption/title/number styling #2643 
- [ ] Headers #2644 
- [ ] Chapter Outline / Introduction #2655
- [ ] Section number treatment #2710 
- [ ] Learning Objectives #2711 
- [ ] Tables #2741 (mostly default style, `top-titled`)  ** utilizes a lot of content driven alignment for text
- [ ] Footnotes #2773
- [ ] Blockquotes #2749 

### [Cardboard asset folder for icons.](https://drive.google.com/drive/folders/1wsO8nLf7QJXj6YnB1pmjPle0hVYwMoyP)
Feature-like things:
- [ ] Student Profile (`<note class="student-profile">`) - uses #2737 with option 4
- [ ] Application (`<note class="application">`) - uses #2737 with option 5 icon https://drive.google.com/file/d/1QkZHu0sGGcZWc5FY6cfmPa-b79X0e2Mz/view?usp=sharing 
- [ ] Activity (`<note class="activity">`) - uses #2737 with option 3 icon https://drive.google.com/file/d/1rqjZpGr5BPLtvWpBKaufULvzmXl7vEpa/view?usp=sharing
- [ ] Analysis Queston (`<note class="analysis-question">`) - uses #2737 with option 2 icon https://drive.google.com/file/d/1znnLBlJViwAmAMNM1D8rGynnTSsZnu5K/view?usp=sharing
- [ ] What Students Say (`<note class="what-students-say">`) - uses #2737 option 3 icon https://drive.google.com/file/d/1g-BiNNtEMH6UKgetLBy7FrCKVLa8zBu5/view?usp=sharing
- [ ] Get Connected (`<note class="get-connected">`) - uses #2737 option 2 icon https://drive.google.com/file/d/16SoDMSGKfmCz4aed86kgMF3v4dtWkTq6/view?usp=sharing

End of Chapter Content
- [ ] #2774 

End of Book Content
- [ ] Appendices (they exists, follow header schema set from header issue referenced above)
- [ ] Index #2746

# Tagging Legend
https://docs.google.com/spreadsheets/d/19StRe6IQatNoucq2E1w4Vd1N1A-lOl5iJzymbKFwbKg/edit#gid=0

**Comment by wilkus27** [comment]
@lwtchu I think there is wrong link in the description. It leads to College Success. Could you confirm that this link: https://katalyst01.cnx.org/contents/Tgl3H6iq@9.4:HFQiJQgd@7/Introduction is the proper one?

**Comment by lwtchu** [comment]
@wilkus27 oops sorry! i updated the card
