### ISSUE TITLE
Add Principles of Management/Organizational Behavior (80%) to Cardboard Theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2863]
# Link to content
-  Principles of Management https://katalyst01.cnx.org/contents/w6yyq31c@10.5:Bgbu38Eg@6/Introduction
- Organizational Behavior https://katalyst01.cnx.org/contents/LZQauaxb@7.5:5BErM-24@2/Introduction - OB shares modules with POM. It has some of its own content as well. I would just take a small pass at OB to make sure things appear correctly when we test at completion.

# General Notes 

# Design elements in the title

General things:
- [x] Table of Contents #1740 - uses the blue version
- [x] Splash image #2642  - uses blue version; city scape icon
- [x] Figure caption/title/number styling #2643 
- [x] Headers #2644 
- [x] Chapter Outline / Introduction #2655
- [x] Section number treatment #2710 
- [x] Learning Objectives #2711 - titled "Learning Outcomes"
- [x] Tables #2741 (mostly default style, `top-titled`)  ** utilizes a lot of content driven alignment for text
- [x] Footnotes #2773 (there are two in chapter 14.3 Process Theories...)
- [x] References #2800

#### Feature-like things:
- [x] Exploring Managerial Careers (`<note class="exploring-manager-careers">`) - uses #2737 with option 4 - exact same as "Exploring Business Careers" but this is titled "Exploring Managerial Careers" be sure to test with `<title>` in the note
- [x] Concept Check (`<note class="concept-check">`) - uses #2737 with option 5 icon  https://drive.google.com/file/d/1QkZHu0sGGcZWc5FY6cfmPa-b79X0e2Mz/view?usp=sharing be sure to test with `<title>` in the note
- [x] Sustainability and Responsible Management (`<note class="sustainability-responsible">`) - uses #2737 with option 2 icon https://drive.google.com/file/d/1-p4uIGpJCz3-DmEiBKU5ukAheA48Owk_/view?usp=sharing be sure to test with `<title>` in the note
- [x] Managerial Leadership (`<note class="managerial-leadership">`) - uses #2737 with option 2 icon https://drive.google.com/file/d/1WZm0hAvgzLkuqNjOqDYEQkIlgNDd8HtK/view?usp=sharing be sure to test with `<title>` in the note
- [x] Ethics in Practice (`<note class="ethics-in-practice">`) - uses #2737 with option 2 icon https://drive.google.com/file/d/1znnLBlJViwAmAMNM1D8rGynnTSsZnu5K/view?usp=sharing be sure to test with `<title>` in the note
- [x] Managing Change (`<note class="managing-change">`) - uses #2737 with option 2 icon https://drive.google.com/file/d/1a0vuzLNzFziOquwJM6qoUJMlWxfSXgsL/view?usp=sharing be sure to test with `<title>` in the note
- [x] Catching the Entrepreneurial Spirit (`<note class="catching-spirit">`) - uses #2737 with option 2 icon https://drive.google.com/file/d/1JELPOVCO7AimoAHHh8JES333XVY9eO3I/view?usp=sharing be sure to test with `<title>` in the note

#### End of Chapter Content
- [x] Key Terms `<section class="key-terms">` (same as #2742) 
- [x] Summary of Learning Outcomes `<section class="section-summary">` #2782 
- [x] Chapter Review Questions `<section class="chapter-review">` #2884 
- [x] Management Skills Application Exercises `<section class="manage-skills">` - same as #2884 but with this icon https://drive.google.com/file/d/169_IQ6DAi8qsAGZv152QHVtSerJIp1z_/view?usp=sharing
- [x] Managerial Decision Exercises `<section class="manage-exercises">` - same as #2884 but with this icon https://drive.google.com/file/d/1HmkBOwnzFJX3dktyuzvCNYRSoVo8KSsY/view?usp=sharing
- [x] Critical Thinking Case `<section class="critical-thinking">` - same as #2789 from Intro to Business

#### End of Book Content
- [x] References (see above)
- [x] Index #2746

# Tagging Legend
https://docs.google.com/spreadsheets/d/1Mo9_YUzsXKlOfLLcGRWUkWOzIoqJ703lnToRzy4r9QE/edit#gid=0

**Comment by ajluk** [comment]
Hi @lwtchu, by "take a small pass at OB" did you mean that we should test these two books simultaneously when implement features or do you prefer to open a separate card for this book after finish Principles of Management and test all features?

**Comment by lwtchu** [comment]
@ajluk when this card is done, we'll do a small pass on OB. when we move the entire card to testing, i'll add that step in. i'll update the above to clarify.

**Comment by ajluk** [comment]
@lwtchu So now I should focus on just PM and when it will be finished there will be some card open to test OB right? I'm asking just to be sure we're on the same page.

**Comment by lwtchu** [comment]
@ajluk yes - just focus on PM

**Comment by brittweinstein** [comment]
@ajluk I'm moving this card back into the epics pipeline since it doesn't seem that all work for PoM is complete. Is this the case?

**Comment by ajluk** [comment]
@brittweinstein Yes, that's right thank you! I have a question about issues that has been created separately for Introduction page for Principles of Management (https://github.com/openstax/cnx-recipes/issues/2977), https://github.com/openstax/cnx-recipes/issues/2980 because I have created one big issue to cover all the features on Introduction page and just linked the documentation cards there. This is the issue https://github.com/openstax/cnx-recipes/issues/3058 Can I just link there the ones you have created as well and set them as in progress?

**Comment by lwtchu** [comment]
@andymuddimer https://openstax.slack.com/archives/C0FU3MARF/p1607619189254500?thread_ts=1607613958.251900&cid=C0FU3MARF 

here's the pdf - known issue is the large images. please review witht he existing pdf on the site and ping me if anything looks weird so we can open cards. thank u

**Comment by lwtchu** [comment]
I believe andy is done testing
