### ISSUE TITLE
Add Entrepreneurship (80%) to the Cardboard Theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2885]
# Link to content
-  https://katalyst01.cnx.org/contents/d380510e-6145-4625-b19a-4fa68204b6b1

# General Notes 

# Design elements in the title
Since this is the first title, there will be a lot more work with this title than others.

General things:
- [x] Table of Contents #1740
- [x] Splash image #2642 
- [x] Figure caption/title/number styling #2643 
- [x] Headers #2644 
- [x] Chapter Outline / Introduction #2655
- [x] Section number treatment #2710 
- [x] Learning Objectives #2711 
- [x] Tables #2741 (mostly default style and some `text-heavy`, `top-titled`) 
- [x] Footnotes #2773

### [Cardboard asset folder for icons.](https://drive.google.com/drive/folders/1wsO8nLf7QJXj6YnB1pmjPle0hVYwMoyP)
Feature-like things:
- [x] Are You Ready? (`<note class="are-you-ready">`) - uses #2737 with color option 3
- [x] What Can You Do? (`<note class="what-can-do">`) -  uses #2737 with color option 3
- [x] Link to Learning (`<note class="link-to-learning">`) - uses #2737 with color option 1
- [x] Entrepreneur In Action (`<note class="entrepreneur-in-action">`) - uses #2737 with color option 2
- [x] Work It Out (`<note class="work-it-out">`) - uses #2737 with color option 2

End of Chapter Content
- [x] Key Terms (`class="key-terms"`) #2742 
- [x] Summary (`class="section-summary"`) #2743
- [x] Review Questions (`class="review-questions"`) #2744 (same specs different title)
- [x] Discussion Questions (`class="discussion-questions"`) #2744  (same specs, different title. this doesn't have the multiple choice list as well but spacing should be the same between the exercises. icon: https://drive.google.com/file/d/1lb8jseP8ES7W7wqmr4uH2gb2UNnCFJ-Z/view?usp=sharing)
- [x] Case Questions (`class="case-questions"`) - same as discussion questions but with this icon: https://drive.google.com/file/d/1tZDE2I5JPF6Ggo676xs79VSs4izviUKQ/view?usp=sharing
- [x] Suggested Resources `class="suggested-resources"`  #2886

End of Book Content
- [x] Appendices (follow header schema set from header issue referenced above)
- [x] Index #2746

# Tagging Legend
https://docs.google.com/spreadsheets/d/1iY_BXc-Uj-0mtfdQw1rwS1HQ1DElW5m6J037SIQSRcI/edit#gid=0

**Comment by ajluk** [comment]
@lwtchu The documentation issue link for Discussion Questions and Case Questions is pointing to some closed issue for Elementary Algebra (#2700) I guess it is by mistake and the correct link should be #2744 as it is in the Review Questions specs. Please let me know if it's different.

**Comment by lwtchu** [comment]
@ajluk thank you i updated the main post.

**Comment by lwtchu** [comment]
@andymuddimer testing ready: https://openstax-cops-artifacts.s3.amazonaws.com/col29104-latest-production-635.pdf

same as before - please go thru and check against the existing pdf. thanks!
