### ISSUE TITLE
(!!! WIP !!!) Add Accounting (80%) to the Cardboard Theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#2887]
# Link to content
-  Volume 1 https://katalyst01.cnx.org/contents/mrS6bR5I@5.2:qv6kYQJ7@3/Why-It-Matters
- Volume 2 https://katalyst01.cnx.org/contents/kg0cimBs@15.1:feO1bURf@4/Why-It-Matters

# General Notes 

# Design elements in the title
Since this is the first title, there will be a lot more work with this title than others.

General things:
- [ ] Table of Contents #1740
- [ ] Splash image #2642 
- [ ] Figure caption/title/number styling #2643 
- [ ] Headers #2644 
- [ ] Chapter Outline / Introduction #2655
- [ ] Section number treatment #2710 
- [ ] Learning Objectives #2711 
- [ ] Tables #2741 (mostly default style and some `text-heavy`, `top-titled`) 
- [ ] Footnotes #2773

### [Cardboard asset folder for icons.](https://drive.google.com/drive/folders/1wsO8nLf7QJXj6YnB1pmjPle0hVYwMoyP)
Feature-like things:
- [ ] Are You Ready? (`<note class="are-you-ready">`) - uses #2737 with color option 3
- [ ] What Can You Do? (`<note class="what-can-do">`) -  uses #2737 with color option 3
- [ ] Link to Learning (`<note class="link-to-learning">`) - uses #2737 with color option 1
- [ ] Entrepreneur In Action (`<note class="entrepreneur-in-action">`) - uses #2737 with color option 2
- [ ] Work It Out (`<note class="work-it-out">`) - uses #2737 with color option 2

End of Chapter Content
- [ ] Key Terms (`class="key-terms"`) #2742 
- [ ] Summary (`class="section-summary"`) #2743
- [ ] Review Questions (`class="review-questions"`) #2744 (same specs different title)
- [ ] Discussion Questions (`class="discussion-questions"`) #2700 (same specs, different title. this doesn't have the multiple choice list as well but spacing should be the same between the exercises. icon: https://drive.google.com/file/d/1lb8jseP8ES7W7wqmr4uH2gb2UNnCFJ-Z/view?usp=sharing)
- [ ] Case Questions (`class="case-questions"`) - same as discussion questions but with this icon: https://drive.google.com/file/d/1tZDE2I5JPF6Ggo676xs79VSs4izviUKQ/view?usp=sharing
- [ ] Suggested Resources `class="suggested-resources"`  #2886

End of Book Content
- [ ] Appendices (follow header schema set from header issue referenced above)
- [ ] Index #2746

# Tagging Legend
https://docs.google.com/spreadsheets/d/1aWsED6fvRFulOfzWIGN3d9TX5gQVeancD43wcl2W6-4/edit#gid=0

**Comment by brittany-johnson** [comment]
@brittweinstein Let's save this epic for Kendra and Mary Jo!
