### ISSUE TITLE
Code Freeze Checklist 

### ISSUE THREAD

**Issue by brittany-johnson** [openstax/cnx-recipes#3074]
# A checklist for code freeze Fridays. 
[Link to milestone calendar with dates of upcoming freezes. ](https://app.zenhub.com/workspaces/ce-styles-5cdc84baee941c07853fbbf2/milestones)

## cnx-recipe freeze
- [x] [Tag cnx-recipes](https://openstax.atlassian.net/wiki/spaces/CE/pages/506101774/cnx-recipes+release+process)
- [x] [(If necessary) Tag oer.exports](https://openstax.atlassian.net/wiki/spaces/CE/pages/506068993/oer.exports+release+process)
- [ ] [Release COPS](https://github.com/openstax/output-producer-service/blob/master/docs/operations/updating_the_stack.rst)
- [x] Post update in #books-and-candles on Slack
- [ ] Create a new checklist for the next milestone

## kitchen freeze
TBA
