### ISSUE TITLE
Add Introduction to Sociology 2e (80%) to the Cosmos Theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3152]
# Link to content
- https://katalyst01.cnx.org/contents/AgQDEnLI@14.1:TrIRM88K@9/Introduction-to-Sociology
- Note: this is one of the higher priority titles because we are planning to do a _Sociology 3e_ this year (2021).

# General Notes 
## Font links
- IBM Plex Serif https://fonts.google.com/specimen/IBM+Plex+Serif?query=ibm+plex+seri#standard-styles
- IBM Plex Sans https://fonts.google.com/specimen/IBM+Plex+Sans?query=ibm+plex
- Archivo https://fonts.google.com/specimen/Archivo?query=archivo
- Archivo Black https://fonts.google.com/specimen/Archivo+Black?query=archivo+black

## Theme assets folder
- https://drive.google.com/drive/u/0/folders/1r-6jPOZZNRL35fhbSgTn6cT5CiQMRn-2

# Design elements in the title

General things:
- [x] Generic things to pull from other titles - Documentation: #3173 Working card: #3174
- [x] Table of Contents - Documentation: #3154  Working card: #3155
- [x] Headers - Documentation: #3164 Working card: #3165 
- [x] Preface #3264 
- [x] Splash image - Documentation: #3171 Working card: #3172 
- [x] Learning Objectives - Documentation: #3175 Working card: #3176 
- [x] Introduction - Documentation #3191 Working card: #3192 
~- [ ] Footnotes - Documentation #3181 Working card: #3182~
- [x] Figure & figure title/captions - Documentation #3183 Working card: #3184 
- [x] Tables - Documentation: #3185 Working card: #3186 
- [x] Blockquotes - Documentation #3276 Working Card: #3404 

### [Cosmos asset folder for icons.](https://drive.google.com/drive/folders/1r-6jPOZZNRL35fhbSgTn6cT5CiQMRn-2?usp=sharing)
Feature-like things:
Iconned box note documentation: #3193 / Boxed note documentation: #3194
- [x] Sociology in the Real World - #3197 
- [x] Social Policy & Debate #3199
- [x] Sociological Research #3200 
- [x] Big Picture #3201 

End of Chapter Content
- [x] Key Terms/Glossary - Documentation: #3206 Working Card: #3207
- [x] Section Summary - Documentation: #3209 Working Card: #3210 
- [x] Section Quiz - Documentation: #3211  Working Card: #3212 
- [x] Short Answer - Documentation #3211 Working Card: #3213 
- [x] Further Research - Documentation #3214 Working Card: #3215
- [x] References - Documentation #3214 Working Card: #3216
 
End of Book Content
- [x] Index - Documentation: #3217 Working Card: ##3218
- [ ] Answer Key - TBD - it is currently suppressed, need to decide whether or not we will unsuppress it for 3e

# Prior to release check list
- [ ] Release to CORGI (fka COPS) #3219
- [ ] Alert Larissa after CORGI release (send this card to specs review). Larissa will have testing documentation.
- [ ] Larissa/QA/etc to test and open cards in cnx-recipes and tag `@lwtchu` 

# Tagging Legend
https://docs.google.com/spreadsheets/d/1cojrRJC4bkf7gK12Wbtj_rbs_lBQc9vc2Lt6iOFIkM0/edit#gid=0
