### ISSUE TITLE
Due 3/5 - Add English Composition (80%) to the Cosmos Theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3483]
# Link to content
- This is a new book. Link forthcoming. Please do not work on this until you have talked to me.
- Test content: https://legacy-content06.cnx.org/content/col10001/latest/

# General Notes 
## Font links
- IBM Plex Serif https://fonts.google.com/specimen/IBM+Plex+Serif?query=ibm+plex+seri#standard-styles
- IBM Plex Sans https://fonts.google.com/specimen/IBM+Plex+Sans?query=ibm+plex
- Archivo https://fonts.google.com/specimen/Archivo?query=archivo
- Archivo Black https://fonts.google.com/specimen/Archivo+Black?query=archivo+black
- Courier Prime https://fonts.google.com/specimen/Courier+Prime?preview.text_type=custom#about

## Theme assets folder
- https://drive.google.com/drive/u/0/folders/1r-6jPOZZNRL35fhbSgTn6cT5CiQMRn-2

# Design elements in the title

General things:
- [ ] Generic things to pull from other titles - Documentation: #3173 Working card: #3487
- [x] Table of Contents - Documentation: #3154  Working card: #3485
- [ ] Headers - Documentation: #3164 Working card: #3486
- [x] Splash image - Documentation: #3171 Working card: #3488
- [x] Chapter Outline - Documentation #3175 Working card: #3484
- [x] Section Learning Outcomes - Documentation #3175  Working card: #3489
- [x] Introduction -  Documentation #3191 Working card: #3507
- [x] Figure & figure title/captions - Documentation #3183 Working card: #3508
- [x] Tables - Documentation: #3185 Working card: #3509  
- [x] Blockquotes - Documentation #3276 Working Card #3510 
- [x] Footnotes: Documentation # 3181 Working Card # need to check if there's any footnotes
- [x] **NEW** functionality Paragraph Icon Annotation - Documentation & Working card #3490
- [x] **NEW** funcationaly Literacy Narrative Trailblazer - Documentation & Working card #3513 - i might need to tweak the content for you
- [x] **NEW** Font treatments for Annotated and Public Domain texts - #3525 
- [x] **NEW** Writing Process Sections - #3599 
- [x] Exercises from Tutor - #3523
- [x] Styling Exercises - #3653

### [Cosmos asset folder for icons.](https://drive.google.com/drive/folders/1r-6jPOZZNRL35fhbSgTn6cT5CiQMRn-2?usp=sharing)
Feature-like things:
- [ ] Living by Their Own Words - Documentation #3193 Working card #3524

End of Chapter Content
- [x] Further Reading - Documentation #3214 Working card #3541 
- [x] Works Cited - Documentation #3214 Working Card #3542
- [x] Works Consulted - Documentation #3214 Working card #3543
 
End of Book Content
- [ ] Appendices - TBD HANDBOOK
- [x] Index - Documentation: #3217 Working Card: #3544

# Prior to release checklist
- [ ] Release to CORGI #3545
- [ ] Alert Larissa once PRs are merged so she can generate locally
- [ ] Larissa to create survey for authors

# Tagging Legend
https://docs.google.com/spreadsheets/d/1AAlU_09uI2jjOv4K-kDKK_gfGjhfAk0li8hyFvP7-Gk/edit?usp=sharing

**Comment by brittany-johnson** [comment]
There isn't a working card for footnotes so I'll just put the screenshot here: 
![Screen Shot 2021-03-03 at 4 52 05 PM](https://user-images.githubusercontent.com/24909007/109883298-d3e9d400-7c40-11eb-87ac-d2363132fb89.png)

**Comment by lwtchu** [comment]
** Will test everything when it goes to staging.
