### ISSUE TITLE
Add Polish Psychology to template

### ISSUE THREAD

**Issue by ajluk** [openstax/cnx-recipes#3538]
@MartaSztuka There you need to test all the main elements that were styled within the cosmos theme in Psychology to check hot they look in Psychologia:
General things:

- [x] Generic things to pull from other titles - Documentation: #3173 Working card: #3261
- [x] Table of Contents - Documentation: #3154 Working card: #3262
- [x] Headers - Documentation: #3164 Working card: #3263
- [x] Preface #3266 - brak w obecnym kontencie na `katalyst 01`
- [x] Splash image - Documentation: #3171 Working card: #3267
- [x] Chapter Outline - Documentation: #3175 Working card: #3268
- [x] Learning Objectives - Documentation #3175 Working card: #3269 - "TREŚĆ ROZDZIAŁU"
- [x] Introduction - Documentation #3191 Working card: #3270
- [x] Figure & figure title/captions - Documentation #3183 Working card: #3271
- [x] Tables - Documentation: #3185 Working card: #3272
- [x] Blockquotes - Documentation #3276 Working Card #3277

Cosmos asset folder for icons.

Feature-like things:
Iconned box note documentation: # 3193 / Boxed note documentation: # 3194 / Condensed icon note: # 3235

- [x] Link to Learning #3273 - "Sięgnij po więcej"
- [x] Everyday Connection #3274 - "Wokół nas"
- [x] What Do You Think? #3275 - "Co o tym sądzisz?"
- [x] Dig Deeper #3278 - "Poznaj szczegóły"
- [x] Connect the Concepts #3279 - "Połącz wątki"

End of Chapter Content

- [x] Key Terms/Glossary - Documentation: #3206 Working Card: #3280 - "Kluczowe pojęcia"
- [x] Section Summary - Documentation: #3209 Working Card: #3281 - "Podsumowanie"
- [x] Review Questions - Documentation: #3211 Working Card: #3283 - "Sprawdź wiedzę"
- [x] Critical Thinking Questions - Documentation #3211 Working Card: #3284 - "Ćwicz myślenie krytyczne"
- [x] Further Research - Documentation #3211 Working Card: #3285 - "Rozwijaj się"

End of Book Content

- [x] Index - Documentation: #3217 Working Card: #3288 - "SKOROWIDZ NAZWISK", "SKOROWIDZ RZECZOWY", "SKOROWIDZ TERMINÓW
OBCOJĘZYCZNYCH"
- [x] References - Documentation #3244 Working card #3287 - "Bibliografia"

**Comment by MartaSztuka** [comment]
### PASSED
#### GENERIC THINGS
##### Table of Contents![Screenshot from 2021-02-23 13-35-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/6f2abd4f-e37d-4c39-9382-a1008932872c)
#####  Headers![Screenshot from 2021-02-23 13-35-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/cadd240f-a3df-4674-8405-b7c34bfd574e)
#####  Preface (brak w obecnym kontencie na katalyst 01)
##### Splash image![Screenshot from 2021-02-23 13-36-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/13b79e8b-29ec-4f09-96a4-b780355ccc5d)
##### Chapter Outline![Screenshot from 2021-02-23 13-36-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/a837c858-4e2f-47b5-baac-3a13c6af08e7)
##### Introduction![Screenshot from 2021-02-23 14-28-21.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/633c3090-c8f7-442b-b4bf-25eab7297136)
##### Figure & figure title/captions![Screenshot from 2021-02-23 14-27-56.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/9609b543-f139-4b98-a1eb-48256d57ffcc)
##### Blockquotes
#### NOTES
##### "Sięgnij po więcej"![Screenshot from 2021-02-23 14-30-35.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d3394f0f-4fe2-41fd-bee1-365794fd093d)
##### "Wokół nas"![Screenshot from 2021-02-23 14-31-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e9e5ad0d-b31b-4636-a5de-65ee2356e7c7)
##### "Co o tym sądzisz?"![Screenshot from 2021-02-23 14-31-43.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3d7f5e40-1037-46a0-84ac-12aa4df9385f)
##### "Poznaj szczegóły"![Screenshot from 2021-02-23 14-31-22.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/4609ff46-01f0-4d8b-9fd0-c64c6e36e6d4)
##### "Połącz wątki"![Screenshot from 2021-02-23 14-32-06.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/df369172-66b4-4a28-be91-12439c278a4a)
#### END OF CHAPTER
##### Key Terms![Screenshot from 2021-02-23 14-32-27.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/bbff81c7-ebc2-4662-9c45-9e23581ebb36)
##### Section Summary![Screenshot from 2021-02-23 14-32-50.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/887cde3f-b975-4dae-b6fb-8b0511ed498f)
##### Review Questions![Screenshot from 2021-02-23 14-33-09.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/d8885321-0a94-424a-85fa-a2c661d34d52)
##### Critical Thinking Questions![Screenshot from 2021-02-23 14-33-24.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ee51f795-3c60-4d43-9ef7-65a0979f0ca9)
##### Further Research![Screenshot from 2021-02-23 14-33-38.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8e63bf88-a41c-4543-ba6d-4f10c64b5c03)
##### References![Screenshot from 2021-02-23 14-34-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/8f3bbee8-71b2-461b-a75a-4c2bc52e0c17)

**Comment by MartaSztuka** [comment]
#### FAILED
@ajluk those could be fixed on production, at least some of them.
##### Learning Objectives is missing in sections
##### Tables![Screenshot from 2021-02-23 14-29-03.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/66a2dd65-f370-49b1-ac47-91259fd72911)
##### "SKOROWIDZ NAZWISK" There's random SYMBOLS at the beginning![Screenshot from 2021-02-23 14-34-45.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/e89ea0bc-5fa2-4e7c-bc1c-b5bd483d4f80)
##### "SKOROWIDZ RZECZOWY"![Screenshot from 2021-02-23 14-40-07.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/65aabf1d-d3a9-4065-9254-0084aa41a540)
##### "SKOROWIDZ TERMINÓW OBCOJĘZYCZNYCH" SYMBOLS issue, also it's chaotic (content issue?)![Screenshot from 2021-02-23 14-37-32.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/3e68e8f2-c899-4254-a51f-328c4c76fec4)

**Comment by wilkus27** [comment]
After discusion there is a decision to change design for some of these elements. Here are more informations: https://github.com/openstax/cnx-recipes/issues/3573.

In Learning Objectives and Index there are content issues. There are created separate cards for them. There is also documentation and working card for Tables. So I'm going to close this issue.
