### ISSUE TITLE
DUE 3/12 - Add Anthropology (80%) to Cosmos Theme 

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3546]
# Link to content
- This is a new book. Link forthcoming. Please do not work on this until you have talked to me.
- Test content: https://legacy-content06.cnx.org/content/col10005/latest/

# General Notes 
## Font links
- IBM Plex Serif https://fonts.google.com/specimen/IBM+Plex+Serif?query=ibm+plex+seri#standard-styles
- IBM Plex Sans https://fonts.google.com/specimen/IBM+Plex+Sans?query=ibm+plex
- Archivo https://fonts.google.com/specimen/Archivo?query=archivo
- Archivo Black https://fonts.google.com/specimen/Archivo+Black?query=archivo+black

## Theme assets folder
- https://drive.google.com/drive/u/0/folders/1r-6jPOZZNRL35fhbSgTn6cT5CiQMRn-2

# Design elements in the title

General things:
- [ ] Generic things to pull from other titles - Documentation: #3173 Working card: #3550
- [x] Table of Contents - Documentation: #3154  Working card: #3551
- [x] Headers - Documentation: #3164 Working card: #3552
- [x] Splash image - Documentation: #3171 Working card: #3553
- [x] Chapter Outline - Documentation #3175 Working card: #3554
- [x] Section Learning Outcomes - Documentation #3175  Working card: #3578
- [x] Introduction -  Documentation #3191 Working card: #3579
- [x] Figure & figure title/captions - Documentation #3183 Working card: #3580
- [x] Tables - Documentation: #3185 Working card: #3581 
- [ ] ~Footnotes: Documentation # 3181 Working Card #~ need to check if there's any footnotes
- [ ] Exercises from Tutor - #3588

### [Cosmos asset folder for icons.](https://drive.google.com/drive/folders/1r-6jPOZZNRL35fhbSgTn6cT5CiQMRn-2?usp=sharing)
Feature-like things:
- [x] Ethnographic Sketches - Documentation #3194 Working card #3582
- [x] Mini-Fieldwork Activity - Documentation #3194 Working card #3583
- [x] Profiles in Anthropology - Documentation #3194 Working card #3584 
- [x] Video - Documentation #3235 Working card #3585
- [x] Podcast - Documentation #3235 Working card #3586

End of Chapter Content
- [x] Key Terms - Documentation #3206 Working card #3587
- [x] Summary - Documentation #3209  Working card #3589
- [x] Critical Thinking Questions - Documentation #3211 Working Card #3590
- [x] Bibliography - Documentation #3214 Working card #3591
 
End of Book Content
- [x] Index - Documentation: #3217 Working Card: #3592
- [ ] NO ANSWER KEY NO KNOWN APPENDICES

# Prior to release checklist
- [ ] Release to CORGI #3593
- [ ] Alert Larissa once PRs are merged so she can generate locally
- [ ] Larissa to create survey for authors

# Tagging Legend
https://docs.google.com/spreadsheets/d/1hsmExk3DWDdVHwDGelGVsbQEYzmBvWN2rEEyzw--Qzo/edit#gid=0

**Comment by ajluk** [comment]
@ I have checked and in the content there are no footnotes.

**Comment by lwtchu** [comment]
@ajluk oh yes - i was meaning to ask the vendor if they plan on using any

**Comment by lwtchu** [comment]
Closing since we're on nround 2
