### ISSUE TITLE
Add Psychologia to Cosmos Theme

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#3573]
# Link to content
https://katalyst01.cnx.org/contents/84JIUkA_@4.1:rs_ilJom@8/Wprowadzenie

# Design elements in the title

Design is based on Psychology 2e.
- [x] Add to template - Working card https://github.com/openstax/cnx-recipes/issues/3538

Below there are elements that should be styled differently.

- [x] Splash Image - Documentation: https://github.com/openstax/cnx-recipes/issues/3558 Working card: https://github.com/openstax/cnx-recipes/issues/3566
- [x] Chapter Outline - Documentation: https://github.com/openstax/cnx-recipes/issues/3564 Working card: https://github.com/openstax/cnx-recipes/issues/3566
- [x] Headers - Documentation: https://github.com/openstax/cnx-recipes/issues/3559 Working card: https://github.com/openstax/cnx-recipes/issues/3567
- [x] Table of Contents - Documentation: https://github.com/openstax/cnx-recipes/issues/3560 Working card: https://github.com/openstax/cnx-recipes/issues/3568
- [x] Figures - Documentation: https://github.com/openstax/cnx-recipes/issues/3561 Working card: https://github.com/openstax/cnx-recipes/issues/3569
- [x] Link to Learning note - Documentation: https://github.com/openstax/cnx-recipes/issues/3562 Working card: https://github.com/openstax/cnx-recipes/issues/3570
- [x] Tables - Documentation: https://github.com/openstax/cnx-recipes/issues/3563 Working card: https://github.com/openstax/cnx-recipes/issues/3571
- [x] Eoc - Documentation: https://github.com/openstax/cnx-recipes/issues/3565 Working card: https://github.com/openstax/cnx-recipes/issues/3572

**Comment by lwtchu** [comment]
@wilkus27 are these cards done? if so can i close :eyes:

**Comment by wilkus27** [comment]
@lwtchu Yes, it can be closed. Thank you! :relaxed:
