### ISSUE TITLE
DUE 3/19 Add World History (80%) to Cosmos Theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3601]
# Link to content
- This is a new book. Link forthcoming. Please do not work on this until you have talked to me.
- Test content: https://legacy-content03.cnx.org/content/col10004/latest/

# General Notes 
## Font links
- IBM Plex Serif https://fonts.google.com/specimen/IBM+Plex+Serif?query=ibm+plex+seri#standard-styles
- IBM Plex Sans https://fonts.google.com/specimen/IBM+Plex+Sans?query=ibm+plex
- Archivo https://fonts.google.com/specimen/Archivo?query=archivo
- Archivo Black https://fonts.google.com/specimen/Archivo+Black?query=archivo+black

## Theme assets folder
- https://drive.google.com/drive/u/0/folders/1r-6jPOZZNRL35fhbSgTn6cT5CiQMRn-2

# Design elements in the title

General things:
- [ ] Generic things to pull from other titles - Documentation: #3173 Working card: #3613
- [x] Table of Contents - Documentation: #3154  Working card: #3629
- [x] Headers - Documentation: #3164 Working card: #3630
- [x] Splash image - Documentation: #3171 Working card: #3631
- [x] Chapter Outline - Documentation #3175 Working card: #3608
- [ ] Section Learning Objectives - Documentation #3175  Working card: #3611
- [x] Introduction -  Documentation #3191 Working card: #3609
- [x] Figure & figure title/captions - Documentation #3183 Working card: #3612
- [x] Blockquotes - Documentation #3276 Working card: #3614 
- [x] Tables - Documentation: #3185 Working card: #3632 
- [ ] *NEW* Header row in middle of table - Working card #3665
- [ ] Footnotes: Documentation #3181 Working Card #3610
- [x] Exercises from Tutor - #3661 (if you see exercises populated and no blank spaces, close the card)
- [ ] Centered text - Documentation #3654 Working card: #3655 

### [Cosmos asset folder for icons.](https://drive.google.com/drive/folders/1r-6jPOZZNRL35fhbSgTn6cT5CiQMRn-2?usp=sharing)
Feature-like things:
- [x] In Their Own Words - Documentation #3194 Working card #3633
- [x] Dueling Voices - Documentation #3194 Working card #3635
- [x] Beyond the Book - Documentation #3194 Working card #3636
- [x] The Past Meets the Present - Documentation #3194 Working card #3637
- [x] Link to Learning - Documentation #3235 Working card #3634

End of Chapter Content
- [x] Key Terms - Documentation #3206 Working card #3639
- [x] Section Summary - Documentation #3209  Working card #3640
- [x] Review Questions - Documentation #3211 Working Card #3641
- [x] Check Your Understanding  - Documentation #3211 Working Card #3642
- [x] Reflection Questions  - Documentation #3211 Working Card #3643
- [x] Visual-Based Questions - Documentation #3211 Working Card #3644
- [x] Making Connections - Documentation #3211 Working Card #3645
- [x] Thought Provokers - Documentation #3211 Working Card #3646
- [x] Source Questions - Documentation #3211 Working Card #3648
 
End of Book Content
- [x] Index - Documentation: #3217 Working Card: #3649
- [x] Appendix - Working Card: #3650
- [ ] Glossary in Appendix - Working Card #3651
- [x] NO ANSWER KEY!!!!

# Prior to release checklist
- [ ] Release to CORGI #3652
- [ ] Alert Larissa once PRs are merged so she can generate locally
- [ ] Larissa to create survey for authors

# Tagging Legend
https://docs.google.com/spreadsheets/d/1g5AvcbKgzBPgKp68K7HT-iWxZWS3Y6jEvqjqQLDmnEs/edit?usp=sharing
