### ISSUE TITLE
DUE March 26 - Add Finance (80%) to the Cardboard Theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3662]
# Link to content
-  https://legacy-content06.cnx.org/content/col10007/latest

# Design elements in the title

General things:
- [x] Generic things to pull - Documentation #2712 / Working card: #3673 
- [x] Table of Contents - Documentation #1740 / Working card: #3672
- [x] Splash image - Documentation #2642 / Working card: #3670 
- [x] Figure caption/title/number styling - Documentation #2643 / Working card: #3677
- [x] Headers - Documentation #2644 / Working card: #3676 
- [x] Chapter Outline & Introduction - Documentation #2655 / Working card: #3669
- [x] Section number treatment - Documentaiton #2710 / Working card: #3679 
- [x] Learning Outcomes - Documentation #2711 / Working card: #3671
- [x] Tables - Documentation #2741 / Working card: #3674
- [ ] **NEW** Table Caption styling - Documentation & Working card: #3678
- [x] Footnotes - Documentation #2773 / Working Card #3700
- [x] **NEW** Calculator buttons - Documentation & Working card: #3684 
- [x] Equations - Documentation #2894 / Working card: #3697
- [x] **NEW** Stepwise Lists (sort of new - to this theme I think) - Documentation & Working Card: #3701
- [ ] TBD Calculator table - hm let's not do this one right now
- [x] **NEW** Timeline table - Documentation and Working Card #3723 
- [x] **NEW** R code snippet (using highlight.js) - Working Card #3725
- [x] Grey table shading - Working card #3724
- [ ] Verify that exercises are pulled in from exercises.openstax.org (are there exercises or are there errors)

### [Cardboard asset folder for icons.](https://drive.google.com/drive/folders/1wsO8nLf7QJXj6YnB1pmjPle0hVYwMoyP)

Feature-like things:
- [x] Think It Through - Documentation #2737 / Working Card #3698 
- [x] Concepts In Practice  - Documentation: #2737 / Working Card  #3699
- [x] **NEW** Excel Spreadsheet  -  Documentation #3680 / Working Card #3681
- [x] Link to Learning - Documentation #2737 / Working Card #3682

End of Chapter Content
- [x] Key Terms - Documentation #2742 / Working Card #3702 
- [x] Summary - Documentation #2743 / Working Card #3703
- [x] CFA Institute - Working card: #3726
- [x] Multiple Choice - Working card: #3705
- [x] Review Questions - included in #3705
- [x] Problems - included in #3705

End of Book Content
- [x] NO APPENDICES
- [x] NO ANSWER KEY
- [x] Index - Documentation #2746 / Working Card #3717

# Tagging Legend
https://docs.google.com/spreadsheets/d/1aWsED6fvRFulOfzWIGN3d9TX5gQVeancD43wcl2W6-4/edit#gid=0

**Comment by lwtchu** [comment]
Finance Exercise Nicknames + IDs
Finance_16_1_01; ID: 25362
Finance_16_1_02; ID: 25374
Finance_16_1_03; ID: 25363
Finance_16_2_01; ID: 25365
Finance_16_2_02; ID: 25366
Finance_16_2_03; ID: 25375
Finance_16_2_04; ID: 25364
Finance_16_2_05; ID: 25378
Finance_16_3_01; ID: 25367
Finance_16_3_02; ID: 25369
Finance_16_3_03; ID: 25371
Finance_16_3_04; ID: 25379
Finance_16_4_01; ID: 25373
Finance_16_4_02; ID: 25376
Finance_16_4_03; ID: 25380
Finance_16_4_04; ID: 25382
Finance_16_5_01; ID: 25368
Finance_16_5_02; ID: 25370
Finance_16_5_03; ID: 25372
Finance_16_5_04; ID: 25381
Finance_16_5_05; ID: 25383
Finance_16_6_01; ID: 25384
Finance_16_tbd_01; ID: 25377
