### ISSUE TITLE
DUE 4/9 Add Computer Science (80%) to Cardboard Theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3727]
# Link to content
-  https://legacy-content03.cnx.org/content/col10009/latest/

# Design elements in the title

General things:
- [ ] Generic things to pull - Documentation #2712 / Working card: #3728 
- [ ] Table of Contents - Documentation #1740 / Working card: #3729
- [x] Splash image - Documentation #2642 / Working card: #3743
- [x] Figure and table caption/title/number styling - Documentation #2643 / Working card: #3744
- [x] Headers - Documentation #2644 / Working card: #3745 
- [x] Chapter Outline & Introduction - Documentation #2655 / Working card: #3746
- [x] Section number treatment - Documentaiton #2710 / Working card: #3747
- [x] Learning Objectives - Documentation #2711 / Working card: #3748
- [x] Tables - Documentation #2741 / Working card: #3749
- [x] Footnotes - Documentation #2773 / Working Card #3751
- [x] **NEW** Math - Working card: #3752
- [x] **NEW** Python code snippets (using highlight.js) - Working Card #3750
- [x] Middle of table header row - Working card #3753
- [x] Verify that exercises are pulled in from exercises.openstax.org (are there exercises or are there errors)
- [ ] Glossary Appendix #3758

### [Cardboard asset folder for icons.](https://drive.google.com/drive/folders/1wsO8nLf7QJXj6YnB1pmjPle0hVYwMoyP)

Feature-like things:
- [x] Think It Through - Documentation #2737 / Working Card #3754
- [x] Concepts In Practice  - Documentation: #2737 / Working Card  #3755
- [x] Link to Learning - Documentation #2737 / Working Card #3756
- [x] Industry Spotlight - Documentation #2737 / Working Card #3759
- [x] Global Issues in Technology - Documentation #2737 / Working Card #3757
- [x] Technology in Everyday Life - Documentation #2737 / Working Card #3760

End of Chapter Content
- [x] Key Terms - Documentation #2742 / Working Card  #3761
- [x] Summary - Documentation #2743 / Working Card #3762
- [x] Review Questions -  #3766
- [x] Conceptual Questions - included in #3766
- [x] Practice Exercises - included in #3766
- [x] Problem Set A - included in #3766
- [x] Problem Set B - included in #3766
- [x] Thought Provokers - included in #3766
- [x] Labs - included in #3766

End of Book Content
- [ ] YES APPENDICES - please follow regular header stuff
- [ ] NO ANSWER KEY
- [ ] Index - Documentation #2746 / Working Card #3795

# Tagging Legend
https://docs.google.com/spreadsheets/d/1oYks17iKs1UEKBgopqlmyBLcH8b1YmhzlaQXw-QwTQ4/edit?usp=sharing
