### ISSUE TITLE
DUE 4/16 - Add Business Computer Applications BCA (80%) to the Cardboard Theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3772]
# Link to content
-  https://legacy-content03.cnx.org/content/col10017/latest/

# Design elements in the title

General things:
- [x] Generic things to pull - Documentation #2712 / Working card: #3780
- [x] Table of Contents - Documentation #1740 / Working card: #3781
- [x] Splash image - Documentation #2642 / Working card: #3783
- [x] Figure and table caption/title/number styling - Documentation #2643 / Working card: #3784
- [x] Headers - Documentation #2644 / Working card: #3785
- [x] Chapter Outline & Introduction - Documentation #2655 / Working card: #3786
- [x] Section number treatment - Documentaiton #2710 / Working card: #3788 
- [x] Learning Objectives - Documentation #2711 / Working card: #3789
- [x] Tables - Documentation #2741 / Working card: #3790
- [x] Footnotes - Documentation #2773 / Working Card #3791
- [x] Middle of table header row - Working card #3792
- [x] Verify that exercises are pulled in from exercises.openstax.org (are there exercises or are there errors)

### [Cardboard asset folder for icons.](https://drive.google.com/drive/folders/1wsO8nLf7QJXj6YnB1pmjPle0hVYwMoyP)

Feature-like things:
- [x] Link to Learning - Documentation #2737 / Working Card #3773
- [x] Spotlight on Ethics - Documentation #2737 / Working Card #3775
- [x] Real-World Application  - Documentation #2737 / Working Card #3793
- [x] Checkpoint - Documentation #2737 / Working Card #3774

End of Chapter Content
- [x] Key Terms - Documentation #2742 / Working Card  #3796
- [x] Summary - Documentation #2743 / Working Card #3797
- [x] Review Questions - included in #3794
- [x] Conceptual Questions - included in #3794
- [x] Now You Try It  - included in #3794
- [x] Practice Exercises  - included in #3794
- [x] Written Exercises - included in #3794
- [x] Case Exercises - included in #3794
- [x] Extention Exercises - included in #3794

End of Book Content
- [x] Appendix - Documentation #2644 / Working Card #3798
- [x] Index - Documentation #2746 / Working Card #3799

# Tagging Legend
https://docs.google.com/spreadsheets/d/1oYks17iKs1UEKBgopqlmyBLcH8b1YmhzlaQXw-QwTQ4/edit?usp=sharing

**Comment by ajluk** [comment]
@lwtchu I have noticed that figures in Introduction in both chapters are missing `splash` class: 
![image](https://user-images.githubusercontent.com/55203598/113903836-b4127680-97d1-11eb-8358-0ea009897669.png)

**Comment by ajluk** [comment]
@lwtchu I have also question aboout Answer Key, if there should be any, because some exercises and checkpoint notes have solutions?

**Comment by lwtchu** [comment]
@ajluk the splash classes should be added and i'll edit the main card to say there is no answer key (added this to the wrong issue at first)

**Comment by MartaSztuka** [comment]
### PASSED
#### General things
##### Folio structure
![Screenshot from 2021-04-29 09-51-40](https://user-images.githubusercontent.com/47241114/116518447-869c8280-a8d0-11eb-93a2-f57021c726b0.png)
##### Standard link color
![Screenshot from 2021-04-29 09-52-34](https://user-images.githubusercontent.com/47241114/116518524-a5027e00-a8d0-11eb-9799-d5b057860a7f.png)
##### List indentations
![Screenshot from 2021-04-29 09-53-16](https://user-images.githubusercontent.com/47241114/116518612-be0b2f00-a8d0-11eb-9a2c-6efc68e88ca1.png)
##### Side bar in EOC 
![Screenshot from 2021-04-29 09-54-34](https://user-images.githubusercontent.com/47241114/116518736-eeeb6400-a8d0-11eb-9f4c-7b78e69fff18.png)
##### Images are set at 200ppi and auto
![Screenshot from 2021-04-29 10-16-48](https://user-images.githubusercontent.com/47241114/116521255-0841df80-a8d4-11eb-86ca-d11e1681d76b.png)
##### Table of Contents
![Screenshot from 2021-04-29 09-55-24](https://user-images.githubusercontent.com/47241114/116518850-0d515f80-a8d1-11eb-93bf-56101a38149b.png)
##### Splash image
![Screenshot from 2021-04-29 09-55-54](https://user-images.githubusercontent.com/47241114/116518895-1e01d580-a8d1-11eb-94ef-62223b578dbc.png)
##### Figure and table caption
![Screenshot from 2021-04-29 09-56-29](https://user-images.githubusercontent.com/47241114/116518952-3114a580-a8d1-11eb-83a1-2cc1ec15d100.png)
![Screenshot from 2021-04-29 09-56-54](https://user-images.githubusercontent.com/47241114/116518995-3ffb5800-a8d1-11eb-86f2-491d6aaf31a3.png)
##### Headers
![Screenshot from 2021-04-29 09-57-16](https://user-images.githubusercontent.com/47241114/116519062-4ee20a80-a8d1-11eb-842c-d66261e59d2a.png)
##### Chapter Outline & Introduction
![Screenshot from 2021-04-29 09-57-55](https://user-images.githubusercontent.com/47241114/116519139-64573480-a8d1-11eb-95fb-24650c707c51.png)
##### Section number treatment
![Screenshot from 2021-04-29 09-58-41](https://user-images.githubusercontent.com/47241114/116519203-7f29a900-a8d1-11eb-8fcc-819b78c13fc3.png)
![Screenshot from 2021-04-29 09-58-29](https://user-images.githubusercontent.com/47241114/116519210-818c0300-a8d1-11eb-927f-76d903f2836f.png)
##### Learning Objectives
![Screenshot from 2021-04-29 09-59-20](https://user-images.githubusercontent.com/47241114/116519265-97012d00-a8d1-11eb-9d6a-ba22e976de6f.png)
##### Tables
![Screenshot from 2021-04-29 10-00-07](https://user-images.githubusercontent.com/47241114/116519372-b435fb80-a8d1-11eb-9d88-a7560f5b1fd8.png)
##### Footnotes
![Screenshot from 2021-04-29 10-00-25](https://user-images.githubusercontent.com/47241114/116519410-bef09080-a8d1-11eb-8f74-792ff36339c1.png)
##### Middle of table header row
![Screenshot from 2021-04-29 10-01-59](https://user-images.githubusercontent.com/47241114/116519602-f5c6a680-a8d1-11eb-9712-44e9aef7e28f.png)
##### Verify that exercises are pulled in from exercises.openstax.org
![Screenshot from 2021-04-29 10-02-42](https://user-images.githubusercontent.com/47241114/116519691-13940b80-a8d2-11eb-8682-856f92056849.png)
![Screenshot from 2021-04-29 10-02-50](https://user-images.githubusercontent.com/47241114/116519698-15f66580-a8d2-11eb-89a9-2cfe24dccfa3.png)
#### Feature-like things
##### Link to Learning
![Screenshot from 2021-04-29 10-03-59](https://user-images.githubusercontent.com/47241114/116519837-3cb49c00-a8d2-11eb-822f-7cc800b0ceea.png)
##### Spotlight on Ethics
![Screenshot from 2021-04-29 10-04-35](https://user-images.githubusercontent.com/47241114/116519911-5524b680-a8d2-11eb-9e68-c14047328bd4.png)
##### Real-World Application
![Screenshot from 2021-04-29 10-05-49](https://user-images.githubusercontent.com/47241114/116520040-7dacb080-a8d2-11eb-8b20-c83e6d51e0ed.png)
##### Checkpoint
![Screenshot from 2021-04-29 10-05-15](https://user-images.githubusercontent.com/47241114/116519968-6968b380-a8d2-11eb-8ecd-8c9ba542a38e.png)
#### End of Chapter Content
##### Key Terms
![Screenshot from 2021-04-29 10-06-29](https://user-images.githubusercontent.com/47241114/116520123-97e68e80-a8d2-11eb-8705-c5e36738c808.png)
##### Summary
![Screenshot from 2021-04-29 10-07-00](https://user-images.githubusercontent.com/47241114/116520181-ac2a8b80-a8d2-11eb-9835-815aafee3be9.png)
##### Review Questions
![Screenshot from 2021-04-29 10-07-41](https://user-images.githubusercontent.com/47241114/116520245-c06e8880-a8d2-11eb-9475-a457d2a2ddf6.png)
##### Conceptual Questions
![Screenshot from 2021-04-29 10-08-01](https://user-images.githubusercontent.com/47241114/116520271-ccf2e100-a8d2-11eb-9c08-4f789b23a8f3.png)
##### Now You Try It
![Screenshot from 2021-04-29 10-08-17](https://user-images.githubusercontent.com/47241114/116520318-db40fd00-a8d2-11eb-83fc-e8f2a097b5cd.png)
##### Practice Exercises
![Screenshot from 2021-04-29 10-08-43](https://user-images.githubusercontent.com/47241114/116520352-e5fb9200-a8d2-11eb-8610-157548ee7b90.png)
##### Written Exercises
![Screenshot from 2021-04-29 10-08-57](https://user-images.githubusercontent.com/47241114/116520373-eeec6380-a8d2-11eb-8242-d3dc3ecc9494.png)
##### Case Exercises
![Screenshot from 2021-04-29 10-09-19](https://user-images.githubusercontent.com/47241114/116520417-fca1e900-a8d2-11eb-9713-4969d2e6cad6.png)
##### Extention Exercises
![Screenshot from 2021-04-29 10-09-44](https://user-images.githubusercontent.com/47241114/116520456-0b889b80-a8d3-11eb-9c9d-65ded928010e.png)
#### End of Book Content
##### Appendix
![Screenshot from 2021-04-29 10-10-51](https://user-images.githubusercontent.com/47241114/116520579-3377ff00-a8d3-11eb-8bf8-4e3ff1ad304e.png)
##### Index
![Screenshot from 2021-04-29 10-11-08](https://user-images.githubusercontent.com/47241114/116520617-3f63c100-a8d3-11eb-8b0f-ce81c1f41083.png)
