### ISSUE TITLE
DUE 5/7~ Add Contemporary Math (80%) to the corn theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3801]
# Link to content
-  https://legacy-content04.cnx.org/content/col10008/latest/

# Design elements in the title

General things:
- [x] Generic things to pull - Documentation #3802 / Working card: #3803 
- [x] Table of Contents - Documentation #2060 / Working card: #3804
- [x] Splash image - Documentation #1752 / Working card: #3806
- [x] Figure and table caption/title/number styling - Documentation #2185 / Working card: #3807
- [x] Headers - Documentation #2144 / Working card: #3805
- [x] Chapter Outline & Introduction - Documentation #2189 / Working card: #3817
- [x] Learning Objectives - Documentation #2190 / Working card: #3818
- [x] Tables - Documentation #2204 / Working card: #3819
- [ ] Stem plot table - cell shading and colored text #3835 TBD not ready yet
- [x] Examples with titles - Documentation #2209 / Working card #3821
- [ ] Entry cell in table shading - #3839
- [x] Verify that exercises are pulled in from exercises.openstax.org (are there exercises or are there errors)

### [Cardboard asset folder for icons.](https://drive.google.com/drive/folders/1wsO8nLf7QJXj6YnB1pmjPle0hVYwMoyP)

Feature-like things:
- [x] no class notes - Definition & Formulas - Documentation #2191 / Working Card #3820
- [x] Who Knew - Documentation #2200 / Working Card #3827
- [x] Work It Out - Documentation #2256 / Working Card #3830
- [x] Tech Check - Documentation #2208 / Working Card #3828
- [x] People in Mathematics - Documentatioin #2208 / Working card #3826
- [x] Your Turn - Documentation #2200 / Working card #3823
- [x] Video - Documentation #2206 / Working card #3824 
- [x] Traffic Light - Documentation #2179 / Working caard: #3825

End of Section Content - Documentation #2463 / Working Card #3831
- [x] Check Your Understanding
- [x] Exercises

End of Chapter Content
- [x] Key Terms - #3832
- [x] Key Concepts - also in #3832
- [x] Videos - also in #3832
- [x] Formulas - also in #3832
- [x] Projects - #3860
- [x] Chapter Review - included in #3860
- [x] Chapter Test - included in #3860

End of Book Content
- [x] NO APPENDICES
- [x] Answer Key - Working Card #3833
- [x] Index - Documentation #2428 / Working Card #3834

# Tagging Legend
https://docs.google.com/spreadsheets/d/1IHlS8KwoTcLyLEM37Hicdf0XSmPOka5N_vnC09124Dc/edit#gid=0

**Comment by lwtchu** [comment]
Need review and merg to l.l - https://github.com/openstax/cnx-recipes/pull/3850
