### ISSUE TITLE
(Due 6/17) Add Philosophy (80%) to the Cosmos theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3872]
# Link to content
- This is a new book.  Please do not work on this until you have talked to me.
- Test content: https://legacy-content06.cnx.org/content/col10009/latest/

# General Notes 
- We'll be replacing the  R1: `#C31427` with B2: `#0074BC`
- Very similar to Anthropology

## Theme assets folder
- https://drive.google.com/drive/u/0/folders/1r-6jPOZZNRL35fhbSgTn6cT5CiQMRn-2

# Design elements in the title

General things:
- [ ] Generic things to pull from other titles - Documentation: #3173 Working card: #3875
- [ ] Table of Contents - Documentation: #3154  Working card: #3876
- [ ] Headers - Documentation: #3164 Working card: #3877
- [x] Splash image - Documentation: #3171 Working card: #3878
- [x] Chapter Outline - Documentation #3175 Working card: #3879
- [x] Section Learning Objectives - Documentation #3175  Working card: #3880
- [x] Introduction -  Documentation #3191 Working card: #3881
- [x] Figure & figure title/captions - Documentation #3183 Working card: #3882
- [ ] Tables - Documentation: #3185 Working card: #3883

### [Cosmos asset folder for icons.](https://drive.google.com/drive/folders/1r-6jPOZZNRL35fhbSgTn6cT5CiQMRn-2?usp=sharing)
Feature-like things:
- [x] Read Like a Philosopher - Documentation #3194 Working card #3884
- [x] Think Like a Philosopher - Documentation #3194 Working card #3885
- [x] Write Like a Philosopher - Documentation #3194 Working card #3886
- [x] Connections - Documentation #3235 Working card #3887
- [x] Timeline - Documentation #3193 Working card #3888

End of Chapter Content
- [x] Key Terms - Documentation #3206 Working card #3889
- [x] Summary - Documentation #3209  Working card #3890
- [x] Review Questions - Documentation #3211 Working Card #3891
- [ ] Further Reading - Documentation #3214 Working card #3892
- [ ] References  - Documentation #3214 Working card #3893
 
End of Book Content
- [x] Index - Documentation: #3217 Working Card: #3894
- [ ] NO ANSWER KEY NO KNOWN APPENDICES

# Prior to release checklist
- [ ] Alert Larissa once PRs are merged so she can generate locally
- [ ] Larissa to create survey for authors

# Tagging Legend
https://docs.google.com/spreadsheets/d/1KwOezpVrOKy66VsQm4SaxLygzi3cGrPzjjJEfXt63I0/edit#gid=0
