### ISSUE TITLE
(6/28) Add Political Science (80%) to the Cosmos Theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#3895]
# Link to content
- This is a new book.  Please do not work on this until you have talked to me.
- Test content: https://legacy-content06.cnx.org/content/col10012/latest 

# General Notes 
- We'll be replacing the  R1: `#C31427` with B2: `#0074BC`
- Very similar to American Government recipe (citation)

## Theme assets folder
- https://drive.google.com/drive/u/0/folders/1r-6jPOZZNRL35fhbSgTn6cT5CiQMRn-2

# Design elements in the title

General things:
- [ ] Generic things to pull from other titles - Documentation: #3173 Working card: #3896
- [x] Table of Contents - Documentation: #3154  Working card: #3897
- [x] Headers - Documentation: #3164 Working card: #3898
- [x] Splash image - Documentation: #3171 Working card: #3899
- [x] Chapter Outline - Documentation #3175 Working card: #3900
- [x] Section Learning Outcomes - Documentation #3175  Working card: #3901
- [x] Introduction -  Documentation #3191 Working card: #3902
- [x] Figure & figure title/captions - Documentation #3183 Working card: #3903
- [x] Tables - Documentation: #3185 Working card: #3904

### [Cosmos asset folder for icons.](https://drive.google.com/drive/folders/1r-6jPOZZNRL35fhbSgTn6cT5CiQMRn-2?usp=sharing)
Feature-like things:
- [x] Show Me the Data - Documentation #3193 Working card #3907
- [x] Connecting Courses - Documentation #3194 Working card #3908
- [x] Meet a Professional - Documentation #3193 Working card #3909
- [x] 50/50 in 2020 - Documentation #3194 Working card #3910
- [x] What Can I Do? - Documentation #3194 Working card #3911
- [x] Where Can I Engage?  - Documentation #3194 Working card #3912
- [x] Video - Documentation #3235 Working Card #3913

End of Chapter Content
- [x] Key Terms - Documentation #3206 Working card #3914
- [x] Summary - Documentation #3209  Working card #3915
- [x] Review Questions - Documentation #3211 Working Card #3916
- [ ] Suggested Readings - Documentation # 3214 Working card # 3892
 
End of Book Content
- [x] References - Documentation #3244 Working Card #3905 
- [x] Index - Documentation: #3217 Working Card: #3917
- [x] NO ANSWER KEY NO KNOWN APPENDICES

# Prior to release checklist
- [ ] Alert Larissa once PRs are merged so she can generate locally
- [ ] Larissa to create survey for authors

# Tagging Legend
https://docs.google.com/spreadsheets/d/1KwOezpVrOKy66VsQm4SaxLygzi3cGrPzjjJEfXt63I0/edit#gid=0
