### ISSUE TITLE
Add Mikroekonomia to the Cosmos Theme

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#4549]
# Link to content
- content will be available on adaptarr

# General Notes 
## Font links
- IBM Plex Serif https://fonts.google.com/specimen/IBM+Plex+Serif?query=ibm+plex+seri#standard-styles
- IBM Plex Sans https://fonts.google.com/specimen/IBM+Plex+Sans?query=ibm+plex
- Archivo https://fonts.google.com/specimen/Archivo?query=archivo
- Archivo Black https://fonts.google.com/specimen/Archivo+Black?query=archivo+black

## Theme assets folder
- https://drive.google.com/drive/u/0/folders/1r-6jPOZZNRL35fhbSgTn6cT5CiQMRn-2

# Design elements in the title

General things:
- [ ] Generic things to pull from other titles - Documentation: #3173
- [ ] Table of Contents - #4538
- [ ] Headers - #4539
- [ ] Splash image - #4540
- [ ] Chapter Objectives - #4541
- [ ] Chapter Introduction -  #4543 
- [ ] Figure & figure title/captions - #4544
- [ ] Tables - #4545  
- [ ] Blockquotes - #4546
- [ ] Equations - #4547
- [ ] Footnotes: #4548

### [Cosmos asset folder for icons.](https://drive.google.com/drive/folders/1r-6jPOZZNRL35fhbSgTn6cT5CiQMRn-2?usp=sharing)
Feature-like things:
Iconned box note documentation: #3193 / Boxed note documentation: #3194 / Condensed icon note: #3235 
- [ ] Link It Up 
- [ ] Bring It Home #4542  (Included in Introduction)
- [ ] Clear It Up 
- [ ] Work It Out 

End of Chapter Content
- [ ] Key Terms/Glossary - 
- [ ] Key Concepts and Summary - 
- [ ] Self-Check Questions - 
- [ ] Review Questions - 
- [ ] Critical Thinking Questions - 
- [ ] Problems - 
 
End of Book Content
- [ ] Appendices - 
- [ ] Index - 
- [ ] Answer Key -  
- [ ] References -
