### ISSUE TITLE
Add Mikroekonomia to the Cosmos Theme

### ISSUE THREAD

**Issue by MartaSztuka** [openstax/cnx-recipes#4550]
# Link to content
- content will be available on adaptarr

# General Notes 
## Font links
- IBM Plex Serif https://fonts.google.com/specimen/IBM+Plex+Serif?query=ibm+plex+seri#standard-styles
- IBM Plex Sans https://fonts.google.com/specimen/IBM+Plex+Sans?query=ibm+plex
- Archivo https://fonts.google.com/specimen/Archivo?query=archivo
- Archivo Black https://fonts.google.com/specimen/Archivo+Black?query=archivo+black

## Theme assets folder
- https://drive.google.com/drive/u/0/folders/1r-6jPOZZNRL35fhbSgTn6cT5CiQMRn-2

# Design elements in the title

General things:
- [x] Generic things to pull from other titles - #4561
- [x] Table of Contents - #4538
- [x] Headers - #4539
- [x] Splash image - #4540
- [x] Chapter Objectives - #4541
- [x] Chapter Introduction -  #4543 
- [x] Figure & figure title/captions - #4544
- [x] Tables - #4545  
- [x] Blockquotes - #4546
- [x] Equations - #4547
- [x] Footnotes: #4548

### [Cosmos asset folder for icons.](https://drive.google.com/drive/folders/1r-6jPOZZNRL35fhbSgTn6cT5CiQMRn-2?usp=sharing)
Feature-like things:
Iconned box note documentation: #3193 / Boxed note documentation: #3194 / Condensed icon note: #3235 
- [x] Link It Up 
- [x] Bring It Home #4542  (Included in Introduction)
- [x] Clear It Up 
- [x] Work It Out 

End of Chapter Content
- [x] Key Terms/Glossary - #4553
- [x] section summary - #4555
 
End of Book Content
- [x] Appendices - #4557
- [x] Index - 
- [x] Answer Key - #4558
- [x] References -

**Comment by wilkus27** [comment]
Moving Epic to Icebox. Waiting for content changes for equation and appendix.
