### ISSUE TITLE
Baked styles refactor - captions

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4585]
https://docs.google.com/spreadsheets/d/18SoSMPVri-FEzBj9-EwBwICFw9wMtTFIVYile5UQ3xU/edit#gid=901187228

- [x] split general container optional components - General Container component mostly contains OPTIONAL properties. It would be better to split this component into containers of a few types, like it is done in Carnival.
- [x] Change component name from Caption__Title--Label to Caption__TitleLabel.
- [x] Carnival - figure caption divider - check why divider is styled only in figures and in one theme.
- [x] Carnival - caption number - check why table caption is styled differently.
If it should be the same, create one general component for caption number. Larissa's note: I think we can merge it to be the same to keep with consistency.
- [x] Carnival - caption title label - doesn't have to be split into types. 

Note: more detailed lists of things that were done are described in the issues cards.
