### ISSUE TITLE
Baked styles refactor - appendix glossary

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4619]
- [x] Carnival - change files names from Appendix to Appendix Glossary
- [x] Other parts of regular Appendix are styled by other shapes (e.g. PageTitles).
- [x] Carnival - check if section (group) should be styled like in other themes. Now there is only a section wrapper. - Note from Larissa: when you get to this can someone explain? should we approach this in a different way? 
- [x] Unordered list - define component in lists file no appendix one.
- [x] Unordered list - review specs (probably should be styled the same way everywhere).
- [x] In Cosmos there are two additional components. Should they be styled in other themes as well? - note from Larissa - what are the two other components? term and list elements?
- [x] Use one components names convention in every theme.

**Comment by ajluk** [comment]
@lwtchu The section (group) in carnival theme only inherits the margin-bottom (0.7rem) from other common styles: 
![image](https://user-images.githubusercontent.com/55203598/164728228-bc793676-1694-4326-b529-aeddce9c5514.png)
But in cardboard and cosmos the section has it's own margin-bottom set to 1.4rem: 
![image](https://user-images.githubusercontent.com/55203598/164728529-ecbbc501-dfb3-4792-8806-797ba4727e95.png)
Should we standardize it be the same on every theme - which option should we keep then: 0.7 or 1.4rem

**Comment by ajluk** [comment]
@lwtchu about the additional appendix elements styled in cosmos these are list item (`li`) which was created for adding indentation, should we also add the indentation for the other themes?:
![image](https://user-images.githubusercontent.com/55203598/164735159-9f84840c-7ab9-47bd-833d-f29409ccdbb2.png)
and `strong` elemnt which has additional padding-right: 3px set: 
![image](https://user-images.githubusercontent.com/55203598/164735502-134bc0eb-6e75-49b5-b4d2-3d78c0c63ab9.png)
Should we also add the padding to string elements in the other themes? This is how it currently looks in Microbiology (carnival): 
![image](https://user-images.githubusercontent.com/55203598/164735730-308529ce-9bff-45f5-9585-8737f12c612a.png)

**Comment by ajluk** [comment]
One more thing about the `column-gap` between glossary columns, do we also want to standardize it in every theme? In carnival the value of the gap is not set and it looks like this by defult: 
![image](https://user-images.githubusercontent.com/55203598/164738977-540be065-6407-4098-a659-6ca943843f64.png)
In cosmos it is set to `h-spacing(4)` which is equal to 32px and looks like this: 
![image](https://user-images.githubusercontent.com/55203598/164738715-49822614-209e-4826-92b4-b5c623edc636.png)

**Comment by lwtchu** [comment]
@ajluk 
- The section (group) in carnival theme only inherits the margin-bottom (0.7rem) from other common styles -- I think.... let's keep both to 0.7rem. so it takes up less space?
- about the additional appendix elements styled in cosmos these are list item (li) which was created for adding indentation, should we also add the indentation for the other themes << can this be done across all themes?
- strong elemnt which has additional padding-right: 3px set: - let's do this across theme
- let's set a col gap - but can it be a bit smaller? the one in cosmos seems too wide. can we do h-spacing(3) or (2)?

hopefully this is clear...tried to go in order of your questions

**Comment by ajluk** [comment]
@Thank you! It's all clear :relaxed:

**Comment by ajluk** [comment]
@lwtchu Here is how Appendix Glossary looks in Microbiology after the standardization changes (I have used h-spacing(2) for the gap): 
![image](https://user-images.githubusercontent.com/55203598/165321147-32a537df-92de-4f65-9bae-1962454346c9.png)
and World History: 
![image](https://user-images.githubusercontent.com/55203598/165321255-b83b136c-7817-49dd-bc62-93963934600d.png)
I can't actually check computer-science from cardboard theme, because the content is temporarily unavailable. I have a question related to it if these changes can be applied to this book and it can tested later or do you prefer rather styles for it untouched with some comments (It is only book from cardboard which have Appendix Glossary)?

**Comment by ajluk** [comment]
Here is how the Appendix Glossary should look in cardboard in computer-science test content: 
![image](https://user-images.githubusercontent.com/55203598/166882620-d08c6438-4029-475e-b8c3-10bbe6f72ba2.png)

**Comment by ajluk** [comment]
@MartaSztuka Within this issue please test the Appendix Glossary  in: Microbiology, Word History and Computer Science (only these books have this kind of appendix). Test content for compiuer science is available in Larissa branch in repo: https://github.com/openstax/osbooks-introduction-computer-science/tree/larissa-test

**Comment by MartaSztuka** [comment]
#### PASSED
###### Microbiology
![Screenshot from 2022-05-06 13-11-46.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/92f75a5c-0aa5-4a0a-bff8-62513406e280)
###### Word History
![Screenshot from 2022-05-06 13-34-18.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/800e20af-29de-4baa-989e-6eeda55fd004)
###### Computer Science
![Screenshot from 2022-05-06 13-18-05.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fe1e563b-fd9d-4d4e-8659-30ec0345d51d)
