### ISSUE TITLE
baked styles refactor - chapter intro

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4629]
[original card](https://docs.google.com/spreadsheets/d/18SoSMPVri-FEzBj9-EwBwICFw9wMtTFIVYile5UQ3xU/edit#gid=1053045210)

- [x] Carnival - add container component to shapes.
- [x] Cosmos - splash figure image - it's an empty wrapper, but doesn't have any children. Check if it shouldn't be styled any way. If not, remove the component. - AL NOTE: It doesn't need any styling. I have removed it.
- [x] Caption title - check why it's not styled in every shape. AL NOTE: will be fully cover within https://github.com/openstax/cnx-recipes/issues/4656
- [x] Caption title - cosmos - check why it's styled differently in shape with chapter objectives and regular one. AL NOTE: Caption for chapter intro has different specs than regular one. But they should be used by every chapter intro shape.
- [x] Caption background - should we keep this component in chapter intro file or move it to caption's one? - LC NOTE: not sure.... I'm inclined to keep it with the chapter intro. AL NOTE: I have kept it in the chapter intro component file
- [x] Introduction body - use more descriptive name for component.
- [x] Shapes with LO - should be named differently in Cardboard and Cosmos. In Cardboard LO it's just a button with letters LO used in Chapter Outline links. In Cosmos LO it's a Learning Objective element inside Chapter Outline. AL NOTE: Learning Objectives in Chapter Outline is not supported any longer. I have removed this part.
- [x] Carnival - full width shape - There were changes in recipes that remove LO from Chapter Outline. Make sure what is the final decision and whether we should keep LO components in shape. AL NOTE: Learning Objectives in Chapter Outline is not supported any longer. I have removed this part.
- [x] Carnival - full width shape - check why chapter outline objective text is not styled. - this component was used only in Margin Intro shape (assume it didn't need to be styled in Full Intro shape), the name was changed in https://github.com/openstax/cnx-recipes/pull/3763 
- [x] Learning objective abstract list - Carnival and Cosmos - make sure how it should be styled. Define components in lists file. - Done within https://github.com/openstax/cnx-recipes/pull/4582 
- [x] Carnival - with objectives shape - add chapter objectives note body component. added within https://github.com/openstax/cnx-recipes/pull/4582
- [x] Chapter objectives list - Carnival and Cosmos - make sure how it should be styled. Check why it is used in full width shape (which contains Learning Objectives not Chapter Objectives). added within https://github.com/openstax/cnx-recipes/pull/2437  - in the past in College Physics also learning objectives were present in chapter objectives, current recipe doesn't support it
- [x] Define components in lists file.
- [x] Introduction header - move components to titles file. 
- [x] Introduction header - Cosmos - in shape with chapter objectives is styled differently. There is separate component with --Economics flag. It should be named in more descriptive way. Name should tell us what is the difference between header from other shapes.

Questions:
- [x] Shapes for chapter intro are enormous. Should we create separate shape for Splash Figure and Chapter Outline/Objective? LC NOTE: This might be good. Especially since chapter outline/objectives are sometimes different?  AL NOTE: The decision was to keep the splash figure within chapter intro shape and exclude only chapter outline and chapter objectives.

**Comment by ajluk** [comment]
Hi Larissa! I have a question about learning objectives list that were previously present in College Physics chapter outline. I checked it is no longer present in the recipe and the outline currently contains only chapter objectives?:
![image](https://user-images.githubusercontent.com/55203598/167164214-57be817f-2597-4270-bd3d-f5ad8b73f445.png)
Could you confirm if it is the final decision that chapter outline shouldn't contain learning objectives? I check few books which utilize the intro shape which includes styling for it and couldn't found any example, so I guess it should be removed from shape.

**Comment by lwtchu** [comment]
@ajluk i think it's still used in the old college-physics style right?

**Comment by ajluk** [comment]
@lwtchu Yes, that's right, but as I checked there are no learning objectives moved in chapter outline by the recipe anymore in college physics, similarly in cosmos , there styling for learning objectives in chapter outline is not used in any book now, so I was wondering if it can be removed? But I just wanted to confirm with you that the there will be no learning objectives in chapter outline in the future content/recipes?

**Comment by lwtchu** [comment]
@ajluk right there won't be in the future anymore.

**Comment by ajluk** [comment]
Ok. Thank you! I will remove it then. :relaxed:

**Comment by ajluk** [comment]
@lwtchu Could you advise shich books Martashould test within this issue? I think from carnival we should check anatomy, because it has chapter objectives and college physics.

**Comment by lwtchu** [comment]
@ajluk i think this is a good list 🤔

**Comment by ajluk** [comment]
@MartaSztuka Please the test the following books which are posted in the above [comment](https://github.com/openstax/cnx-recipes/issues/4629#issuecomment-1128890472).
