### ISSUE TITLE
baked styles refactor - footnotes

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4678]
- [ ] FootnoteCallShape doesn't have a container component. An empty wrapper can be added to the shape and the selector hardcoded for DefaultFootnoteCall (has an emty selector set in fotnote-settings files). - AL NOTE: I haven't added the container to the shape, because the shape only contains one component and it would break the convention for keeping all selectors in settings files
- [x] components like Border, Title, List and Link can be removed (aren't used in any shape). Their settings aslo need to be removed from footnote-settings files in every theme
- [x] FootnoteMarker and FootnoteCall component only property content can be probably hardocoded to none. It has the same value for every theme.
- [x]  the footnote border styling is defined in _page.scc file in commpon/pdf catalog: @page {  @footnotes {    border-top-color: #000000;    border-top-width: 0.5pt;    border-top-style: solid;    display: block;    margin-top: v-spacing(1);  }}

**Comment by ajluk** [comment]
@lwtchu I have standardized the line-height value if the footnote container to line-height(0) = 1.5rem. It was set to 1rem for unknown reason in carnival and cardboard theme. Here is how they look now:

**Comment by lwtchu** [comment]
@ajluk i think it was set to 1 because it was too much space in between? and with books with long footnotes, things didn't fit?

**Comment by ajluk** [comment]
@lwtchu Thank you! That could be the reason (I couldn't found the issue/pr). So should I keep it as it was set before right?

**Comment by lwtchu** [comment]
@ajluk yeah i think it's ok to standardize to 1rem

**Comment by ajluk** [comment]
@lwtchu Here is how it looks: 
carnival (microbiology)
![image](https://user-images.githubusercontent.com/55203598/170229457-05578442-c6ee-4057-9d34-7ba53989453f.png)
cardboard (marketing)
![image](https://user-images.githubusercontent.com/55203598/170231815-b869db3d-5dd9-47fd-b3d8-5ee17affe672.png)
corn (introductory-statistics)
![image](https://user-images.githubusercontent.com/55203598/170231977-7c60e412-d12c-4f42-8d83-43e65e9020ef.png)
cosmos

**Comment by lwtchu** [comment]
@ajluk perfect thank you

**Comment by ajluk** [comment]
@MartaSztuka Please test one book with footnotes from each theme.

**Comment by MartaSztuka** [comment]
#### PASSED
###### MICROBIOLOGY
![Screenshot from 2022-05-27 14-18-13](https://user-images.githubusercontent.com/47241114/170698010-246a0213-4eb5-452d-9c3d-ecf59d57dc50.png)
###### MARKETING
![Screenshot from 2022-05-27 14-21-44](https://user-images.githubusercontent.com/47241114/170698395-c670f071-701a-4fd3-9070-b0852f513a99.png)
###### STATISTICS
![Screenshot from 2022-05-27 14-24-50](https://user-images.githubusercontent.com/47241114/170698934-24a44b39-58ee-4c51-bc96-538d2f8de868.png)
###### WORD HISTORY
![Screenshot from 2022-05-27 15-16-41](https://user-images.githubusercontent.com/47241114/170706761-688c60f4-dd3a-4a1c-a6a7-3ec10bd92ec8.png)
