### ISSUE TITLE
baked styles refactor - eoc end of chapter

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4683]
- [ ] Eoc container - should we create separate components for containers with columns? - LC yes? so we have 2 and 3?
- [ ] References - there are two types: notes with citations inside modules and whole sections. We move them sometimes to EOC and sometimes to EOB. That's why we should create separate files for references. But references of section type are styled like modules with indentations, so this shape can cover them. In this case, should we create files just for references of note type? - LC: Not sure what is better here 🤔  I'll have to think. maybe whoever works on this can message me -- or discuss with person working on #4684 
- [ ] Corn - column shapes - use section wrappers and remove EocSection__Container component.
- [ ] Modules with indentation - they appear in EOC and EOB. Create separate files for them.
- [ ] Module with type A list - move shape to lists shapes file.
- [ ] Carnival - remove Key Equations and Summary shapes.

Discussion notes; we can talk about it when someone starts working on this?

I would suggest to remove eoc files entirely. Instead we should:
1. Create files for Key Terms.
2. Create files for References of notes type (Endnotes? - if they are named like that everywhere).
3. Discuss where to style References of section type (in references or module with indentation file).
4. Create shape for module with type A list in lists file.
5. Create shape for Eoc table in tables file.
6. Create files for Modules and define there shapes:
  a) ModuleShape - should contain container that adds bottom margin (can be used e.g. for Summary).
  b) ModuleWithIndentationShape
  c) ModuleWithColumnsShape - use in Corn
  These shapes can be used for Eoc and Eob modules.
  All other things are styled separately (headers, lists, tables).
7. Carnival - section with bottom margin - remove
