### ISSUE TITLE
baked styles refactor - references

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4684]
- [ ] Check where chapter area appears. In references of both type or just in note one? Add/ remove this component.
- [ ] Cosmos - References Without Numbering - use section with references class, not general one.
- [ ] See notes of references from #4683 
- [x] Use one name convention across themes.
- [ ] If references are styled in the same way within different themes, try tu use the same properties everywhere. E.g. width of references number sometimes is in rem, and sometimes in inches. Use the same value.

### Edit
After deeper investigation, this is what has to be done. Points from above are not relevant any more.

#### Cardboard
- remove `Endnote` shape and its components from eoc files
- create `ReferencesWithNumberedNotesShape` in references file (apply to intro-business, principles-managment)
- create `ReferencesWithLinkedNotesShape` in references file (apply to bca, business-ethics, marketing)
- remove `appendix-references` files and use `ReferencesWithLinkedNotesShape` to style references from appendix (apply to marketing)
- remove `ModuleWithIndentation` shape and its components from eoc files and move them to module files (there is no book in this theme that uses this shape for references; should be done just for consistency with other themes)

#### Carnival
- remove `ModuleWithIndentation` shape and its components from eoc files and move them to module files
- remove `References` files and style them with `ModuleWithIndentation` shape (apply to anatomy, anthropology)
- standardize indent to `h-spacing(2)`

NOTE:  there are no references of notes type like in Cardboard

#### Corn
- remove `References ` shape and its components from eoc files
- create `ModuleWithIndentation` shape in module files (apply to additive-manufacturing, statistics)
- standardize indent to `h-spacing(2)`
- decrease font size (it's bigger then in other modules now)

NOTE:  there are no references of notes type like in Cardboard

#### Cosmos
- remove shape for references with indents from references files, leave just shapes for references of notes type
- use `ModuleWithIndentation` shape to style references with indents (apply to economics, philosophy, pl-economics, pl-psychology, psychology, sociology)
