### ISSUE TITLE
baked styles refactor - exercises

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4692]
- [x] Create one container component for eoc modules with bottom margin. (Remove containers for multicolumn modules in Corn. In Carnival don't use component from other files.)
  - ALL THEMES
    - Standardize margin bottom for exercise module container `v-spacing(1) = 0.7rem`
- [x] Carnival - EOC Assesments shape - check why there is no component for [data-type="exercise"]. **ALNOTE**: It is an empty wrapper which was just omitted in the shape. I have added it.
- [x] Add everywhere components for injected exercises and style them as regular ones.
- [x] Content exercises - should we create separate shapes for them? Maybe we can reuse module shapes. Investigation needed. If they should have separate shapes, create container component for them and reuse exercise and injected exercise components used in module shapes. Don't create new ones. Remove redundancy. How to avoid using one component a few times in one shape?
    - CARNIVAL
      Reduced exercise shapes to one Exercise Module Shape
    - CARDBOARD
      There was no separate shape created for content exercises.  (There are content exercises in Marketing (Knowlegde Check) which utilized the same shape as eoc exercises)
    - CORN
      Reduce to one Exercise Module Shape
    - COSMOS 
      Refactored to use one ExerciseModuleShape 

- [x] Carnival - remove lists and tables components from shapes. They should be styled separately.
- [x] Carnival - section with bottom margin - check if we need this component. It's not used anywhere else. ALNOTE: This components was created within  [issue](https://github.com/openstax/cnx-recipes/issues/2013) and is still needed for remove section margins inherited from root (0.7rem) for books, where sections in eoc composite pages in exercises don't have section links and the margin makes odd gaps. For exercises with section links the margin is set to `margin-bottom': column-v-spacing(1) = 1.4rem` Need to be checked if we would like to apply such solution for other themes (in a separate issue) Some work has been already done by Natalia within https://github.com/openstax/ce-styles/pull/11/files. 
- [x] Cardboard - remove lists, tables and titles components from shapes. Style them separately. Analyze carefully all three shapes. Do we need all of them? Or we can operate on OPTIONAL properties. Probably they'll be split into smaller pieces after discussion from point 5. ALNOTE: I guess it was meant CORN. In CARDBOARD there no tables, lists in exercise shape.
- [x]  Make sure to style everywhere: a) injected exercises (see point 3.)  b) exercises containers with elements on tops (image/table/list)
- [x] Corn - check if we can remove margin from paragraph, except when next sibling is image or circled list. This work will be done within separate issue: https://github.com/openstax/cnx-recipes/issues/4716

- [x] Images components - should we leave them or style separately? LC: If lists and tables are separate, I think we can keep images separate
- [x] Add support for styling lists in injected exercises - ALL THEMES

**Comment by ajluk** [comment]
@lwtchu I have a question about margin-bottom for eoc modules. In CARNIVAL we reduced the margin bottom for eoc components to `v-spacing(1) = 0.7rem` for space saving, in the other theme is set to v-spacing(2) = 1.4rem. Should we standardize it?

**Comment by ajluk** [comment]
@Stackblocks Within testing this PR please check:

- one book from CARNIVAL with exercises in two column layout (any physics book). Hs-physics would be best because this is the only book in this theme, where also  Content Exercises displayed on the whole page are present (e.g. Check Understanding), 
- CARDBOARD - any book
- CORN - one dev-math (elementary-algebra, intermediate-algebra, prealgebra), precalculus (algebra-trigonometry, precalculus,college-algebra) or precalculus-coreq (college-algebra-coreq) book needs to be checked because these have content and eoc exercises in three columns, college-algebra-coreq needs to be checked also separately because it has Coreq Content exercises present (e.g. Practice Makes Perfect), Alan please also check Contemporary Math (where eoc and content  injected exercises displays on the whole page)
- COSMOS - English Composition (contains injected exercises) + any other book from this theme.
@lwtchu If you have any suggestions about the books which should have been checked please let us know :slightly_smiling_face:
