### ISSUE TITLE
baked styles refactor - lists

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4694]
- [x] Carnival - was done with diferent convention.  Style lists like in other themes.
- [x] Corn - Stepwise lists - create separate shape for them like in Cardboard.
- [x] Carnival - titled lists - create separate shape for them. Make sure if it doesn't appear in other themes.
- [x] Corn - create separate shape for EOS lists.
- [x] Corn - create separate shape for circled lists.  Make sure to style tokens from paragraphs and from labeled lists.
- [x] There are some settings for stepwise and labeled lists in common-style file. Move them to lists components.
- [x] Corn - ListTable shape - remove. Use component in tables shapes.
- [x] Create shapes for figures and tables in lists in corresponding files.

Question:

- [x] Should we complete shapes with missing components?  For example, if in section wrapper there is styled only ordered list, not unordered one etc.

**Comment by ajluk** [comment]
@lwtchu Only in CARNIVAL theme lists have bottom margins added in exercises, solutions, exercise composite pages (0.7rem). Do you think we should standardize and remove the bottom margins from the lists in CARNIVAL because it appeared that we probably don't need them (we don't use them in any of the other themes)?

**Comment by lwtchu** [comment]
@ajluk i think it's because in some cases lists were in feature boxes...and the padding w ould run up to the bottom 

is there a separate way we are implementing padding in feature boxes to where lists could have 0 padding below?

**Comment by ajluk** [comment]
@lwtchu Thank you! I checked the notes components and in the other themes we use paddings especially for Boxed Notes Body. I will remove the margin bottom from lists in notes and add paddings to Boxed Notes Body components in CARNIVAL. About the lists in exercises I guess the margin bottom can be removed since we don't have a special treatment of padding in exercises in the other themes and margins for sections with links are covered in a separate shape. Is that alright?

**Comment by lwtchu** [comment]
@ajluk yes i think that's alright

**Comment by ajluk** [comment]
@lwtchu I ended up adding top and bottom paddings to notes containers (whole note) instead of note body, because for note body it looked odd when the title didn't have any top padding added and it would need more styles changes. So this way it was more clear and easy. Here is how the notes look now vs before this change: 

**BEFORE**:
Anatomy:
![image](https://user-images.githubusercontent.com/55203598/184430089-6f9025d7-19c4-43a2-b8af-ee138ba0488d.png)
![image](https://user-images.githubusercontent.com/55203598/184430115-c1d2cacf-e0aa-4b1f-979f-2c79cd39d4e9.png)
![image](https://user-images.githubusercontent.com/55203598/184430168-7751ebf4-6931-46eb-bf72-2ccd281f3df7.png)

College Physics:
![image](https://user-images.githubusercontent.com/55203598/184430473-f621f70d-5d2e-4970-bfc9-f22885aff504.png)
![image](https://user-images.githubusercontent.com/55203598/184430553-a7d84b5b-7cbb-4009-8513-24163f482bd2.png)
![image](https://user-images.githubusercontent.com/55203598/184430807-dd8330f7-7cb8-412b-9ce2-cbf7a01bd758.png)

NOW:
College Physics:
is it ok for PHET note to have the little more gap between the border and the phet icon?
![image](https://user-images.githubusercontent.com/55203598/184428859-fb1baf0a-019d-4d06-86ab-2044696aae05.png)
![image](https://user-images.githubusercontent.com/55203598/184429135-a6c49157-be67-461c-89e5-4a2fe990b7e5.png)
![image](https://user-images.githubusercontent.com/55203598/184431688-69af6487-95c3-499d-af83-191fb860d349.png)

Anatomy:
![image](https://user-images.githubusercontent.com/55203598/184431026-1f7e70c0-d467-4239-87b6-1bb22c3230a3.png)
![image](https://user-images.githubusercontent.com/55203598/184429462-4f894f4f-1e45-484a-8e8e-5927989df266.png)
![image](https://user-images.githubusercontent.com/55203598/184429495-0a32cfb8-7470-4f1e-bc93-d42a4c972ebb.png)

The number of pages increased only by a few for both books. I haven't check the others. Let me know if this is acceptable or should we rather keep the margins for lists in notes. :slightly_smiling_face:

**Comment by lwtchu** [comment]
@ajluk 🤔 ok i think it should be fine. that way we can keep lists consistent with all of the other themes

**Comment by ajluk** [comment]
@lwtchu Do you have some preference of which books should be tested within this issue?

**Comment by lwtchu** [comment]
let's  focus on the books in production :eyes: world history, principles of economics, marketing and then spot check a book from each theme (doesn't matter w which ones just 1  from each theme)

**Comment by ajluk** [comment]
@lwtchu Thank you! I should be more precise. :facepalm:  I have only cleaned carnival for now within https://github.com/openstax/ce-styles/pull/48 It was much more work to be done there than in the rest of the themes, so I made a separate PR and it is ready to merge. I have opened a separate issue for testing only carnival books: https://github.com/openstax/cnx-recipes/issues/4829? If that's ok, could you advise on what books we should pay attention in carnival?

**Comment by lwtchu** [comment]
@ajluk ah maybe  college physics 2e then 🤔

**Comment by ajluk** [comment]
Ok :+1: and quick spot on the rest? Within this issue also notes should be checked.

**Comment by lwtchu** [comment]
@ajluk ah okay - let's check college physics, A&P, microbio and chem? and spot check a few chapters
