### ISSUE TITLE
baked styles refactor - indent

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4705]
- [x] This shape is used in Polish book.  In Polish texts first line in paragraph has indentation. We should rename this to be more descriptive. Now it might be confused with modules with indentations. **Edit:** remove `indent` files totally; move shape to `module` files
- [x] Use section wrapper from wrappers-components instead of IndentSection.
- [x] Make sure to create this shape in Cosmos and apply it to Polish Psychology and Microecon.

**Comment by wilkus27** [comment]
### Information for tester
Changes are made in new `ce-styles` repo. Please wait with testing until integration with Enki be done.
