### ISSUE TITLE
Add Organic Chemistry (80%) to the Carnival Theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4722]
# Link to content
-  https://github.com/openstax/osbooks-organic-chemistry/tree/Design-Chapter

# Design elements in the title

## Color for header and bands
B3: `#00819A`

General things:
- [x] Generic things to pull - Documentation #4736 / Working card: #4737 
- [x] Table of Contents - Documentation #4730 / Working card: #4731
- [x] Splash image - Documentation #1075 / Working card: #4734
- [x] Figure and table caption/title/number styling - Documentation #1081 / Working card: #4735
- [x] Headers - Documentation #4732 / Working card: #4733
- [x] Chapter Outline & Introduction - Documentation #4738 / Working card: #4739
- [x] Learning Objectives - Documentation #1077 / Working card #4740
- [x] Tables - Documentation #1080 / Working card: #4741
- [x] Color text - Working card #4742
- [x] Verify that exercises are pulled in from exercises.openstax.org (are there exercises or are there errors)
- [x] Assessments structure - #4749
- [x] Worked Examples - Documentation #1793 / Working Card #4745

### [Carnival asset folder for icons.](https://drive.google.com/drive/u/0/folders/1zA3DPstc7Cx1BqtdMYCEB_NGXn1D0XXw)

Feature-like things:
- [x] Why This Chapter? - Documentation #4746 /  Working Card #4748
- [x] Something Extra - Documentation #3966 / Working Card #4750
- [x] Working Problems - Documentation #4746 / Working Card #4751

End of Chapter Content
- [x] Key Terms - #4754 
- [x] Summary ^ covered above
- [x] Summary of Reactions ^ covered above
- [x] Visualizing Chemistry ^ covered above
- [x] Additional Problems ^ covered above
- [x] Practice Your Scientific Analysis and Reasoning ^ covered above

End of Book Content
- [x] YES APPENDICES - please follow regular header stuff
- [x] Answer Key - Documentation #4757 / Working Card #4758
- [x] Index - Documentation #4755 / Working Card #4756

**Comment by lwtchu** [comment]
@Stackblocks pls close this once release is verified on corgi-prod
