### ISSUE TITLE
Add Computer Programming w Python (80%) to Cardboard Theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4863]
# Link to content
-  https://github.com/openstax/osbooks-computer-programming-python
- Branch: main

# Design elements in the title

We tested this on CORGI with Business Ethics recipe and it generates - so you could make a copy. 

General things:
- [x] Generic things to pull - Documentation #2712 / Working card: #4864
- [x] Table of Contents - Documentation #1740 / Working card: #4865
- [x] Splash image - Documentation #2642 / Working card: #4867
- [x] Figure and table caption/title/number styling - Documentation #2643 / Working card: #4870
- [x] Headers - Documentation #2644 / Working card: #4871 
- [x] Chapter Outline & Introduction - Documentation #2655 / Working card: #4872
- [x] Section number treatment - Documentation #2710 / Working card: #4873
- [x] Learning Objectives - Documentation #2711 / Working card: #4874
- [x] Tables - Documentation #2741 / Working card: #4875
- [ ] Python code snippets (using highlight.js) - Documentation #3750 / Working card: #4877
- [x] Verify that exercises are pulled in from exercises.openstax.org (are there exercises or are there errors)

### [Cardboard asset folder for icons.](https://drive.google.com/drive/folders/1wsO8nLf7QJXj6YnB1pmjPle0hVYwMoyP)

Feature-like things:
- [x] Checkpoint - Documentation #2737 / Working Card #4879
- [x] Concepts in Practice - Working Card https://github.com/openstax/cnx-recipes/issues/4880 
- [x] Try It - Working Card #4881

End of Chapter Content
- [x] NONE

End of Book Content
- [x] NO APPENDIX
- [x] Answer Key - Documentation #2748 / Working Card #4878 
- [x] Index - Documentation #2746 / Working Card #4882

# Tagging Legend

**Comment by lwtchu** [comment]
Closing. The python code snippets in a single line, we can deal with after
