### ISSUE TITLE
Pre-Onboarding Tasks

### ISSUE THREAD

**Issue by LostMojo** [openstax/cnx-recipes#4924]
Resources and Documentation to get in order before new hire arrives:

- [ ] GoogleSheet of styles, enki, and cookbook commands
- [ ] Styles & Cookbook naming documentation
- [ ] Ruby Course
- [ ] A document to gather relevant non-internal documentation
