### ISSUE TITLE
Add `nursing-external` Pharmacology, Nutrition, Community-Health Nursing books (80%) into the Carnival Theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#4975]
# Link to content
https://github.com/openstax/osbooks-nursing-external-bundle
https://github.com/openstax/osbooks-nursing-external-bundle/tree/design-chapters

Note: These three titles are going to share the same `nursing-external` recipe. Please call it that.

# Design elements in the title

## Color for header and bands
B3: `#00819A`

### General things:
- [ ] Generic things to pull - Documentation #4736 / Working card: #4976
- [ ] Table of Contents - Documentation #4730 / Working card: #4978
- [ ] Splash image - Documentation #1075 / Working card: #4979
- [ ] Figure and table caption/title/number styling - Documentation #1081 / Working card: #4980
- [ ] Headers - Documentation #4732 / Working card: #4981
- [ ] Chapter Outline & Introduction - Documentation #4738 / Working card: #4982
- [ ] Learning Outcomes - Documentation #1077 / Working card #4983
- [ ] Tables (generic) - Documentation #1080 / Working card: #4984
- [ ] Vertically-tight, text heavy tables - Working card #5007
- [ ] Alternate shading table - Working card #5008
- [ ] No border with header rows table - Working card #5009
- [ ] Blue color text - Working card #5006
- [ ] Verify that exercises are pulled in from exercises.openstax.org (are there exercises or are there errors)
- [ ] Footnotes - Documentation #5010 / Working card #5011

##### Documentation #3235 
- [ ] Link to Learning `link-to-learning` #4986
- [ ] Safety Alert `safety-alert` #4994
- [ ] Clinical Tip `clinical-tip` #4995
- [ ] The Roots of Health Inequities `health-alert` #4998

##### Documentation #3966
- [ ] Healthy People 2030 `healthy-people` #4990
- [ ] Trending Today `trending-today` #4993
- [ ] Media `media-feature` #4999
- [ ] Conversations About Culture `culture-conversations` #4992 
- [ ] Theory in Action `theory-action` #4996
- [ ] Case Reflection `case-reflection` #5000
- [ ] Unfolding Case Study `unfolding-casestudy` #5000
- [ ] Case Study `single-casestudy` #5000

##### Documentation #4746 
- [ ] Special Considerations `special-considerations` #4988
- [ ] FDA Black Box Warning `black-box` #4987
- [ ] Client Teaching Guidelines `client-teaching` #4991
- [ ] Practice Problems `practice-problems` #4997

### End of Chapter Content
- [ ] Key Terms - #5003
- [ ] Summary ^ covered above
- [ ] Review Questions ^ covered above
- [ ] Suggested Readings ^ covered above
- [ ] References ^ covered above

### End of Book Content
- [ ] YES APPENDICES - please follow regular header stuff
- [ ] References - Documentation #3244 / Working card: #5014
- [ ] Answer Key - Documentation #4757 / Working Card #5004
- [ ] Index - Documentation #4755 / Working Card #5005
