### ISSUE TITLE
Add nursing-internal (Clinical, Psychiatric, Fundamentals, Maternal, Med-Surge) Nursing books (80%) into the Carnival Theme

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5053]
# Link to Content
https://github.com/openstax/osbooks-nursing-internal-bundle 
Branch: testcontent 

Note: These five titles are going to share the same `nursing-internal` recipe. Please call it that.

Not to be confused with `nursing-external`. It will be similar though.

# Design elements in the title

## Color for header and bands
B3: `#00819A`

### General things:
- [x] Generic things to pull - Documentation #4736 / Working card: #5058
- [x] Table of Contents - Documentation #4730 / Working card: #5061
- [x] Splash image - Documentation #1075 / Working card: #5062
- [x] Figure and table caption/title/number styling - Documentation #1081 / Working card: #5063
- [x] Headers - Documentation #4732 / Working card: #5064
- [x] Chapter Outline & Introduction - Documentation #4738 / Working card: #5065
- [x] Learning Outcomes - Documentation #1077 / Working card #5066
- [x] Tables (generic) - Documentation #1080 / Working card: #5067
- [x] Verify that exercises are pulled in from exercises.openstax.org (are there exercises or are there errors)
- [x] Footnotes - Documentation #5010 / Working card #5068
- [x] Centered text - Documentation #3654 / Working card #5085
- [x] Indented text - Documentation none found / Working card #5084

##### Documentation (condensed icon note) #3235 
- [x] Link to Learning `link-to-learning` #5069

##### Documentation (iconned note) #3966
- [x] Unfolding Case Study `unfolding-casestudy` #5070
- [x] Real RN Stories `rn-stories` #5072
- [x] Clinical Safety and Procedures (QSEN) `clinical-safety` #5071
- [x] Life-stage and Cultural Context `cultural-context` #5073
- [x] Patient Conversations `patient-conversations` #5074
- [x] Pharmacology Connections `pharma-connections` #5075
- [x] Legal and Ethical Issues `legal-ethical` #5076
- [x] Multidisciplinary Plan of Care `multi-disciplinary` #5077

##### Documentation (uniconned boxed note) #4746 
- [x] Clinical Judgment Measurement Model `clinical-judgment` #5078
- [x] Read the Electronic Health Record `electronic-hr` #5079
- [x] Psychosocial Considerations `psychosocial-considerations` #5080

### End of Chapter Content
- [x] Key Terms - #5081
- [x] Summary ^ covered above
- [x] Assessments ^ covered above
- [x] References ^ covered above

### End of Book Content
- [x] YES APPENDICES - please follow regular header stuff
- [x] Answer Key - Documentation #4757 / Working Card #5082
- [x] Index - Documentation #4755 / Working Card #5083
