### ISSUE TITLE
[Due by May 19 code freeze] Add College Success High School (hs-college-success) recipe to the Cardboard theme (100%)

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5106]
New recipe name `hs-college-success`
Content link: https://github.com/openstax/osbooks-college-success-bundle 
Slugs: college-success, college-success-concise, preparing-for-college-success

**Make a copy of `college-success` recipe and name it `hs-college-success`** 

### New High School specific features
- [x] Family & Friends Matter `family-friends` - normal section, no need for styling / working card #5125 
- [x] Checking In: Your College Readiness Checklist `checking-in` - normal section, no need for styling / working card #5126 
- [x] Student Story `student-story` documentation #2737 / working card  #5107
- [x] The Real Deal `real-deal` documentation #2737 / working card  #5108
- [ ] suppressing in `college-success` recipe

## Testing 
- [ ] features and sections above appear in college-success-high-school and Student Story and The Real Deal are styled
- [ ] features and sections above are not present in `college-success-concise` (not in the `college-success` recipe)

**Comment by openstaxalina** [comment]
Updated root comment above to change Real Deal to **The Real Deal** per author request. The linked issue already says The Real Deal so I didn't touch that one. cc @lwtchu @yblock

**Comment by jbwilson8** [comment]
@lwtchu  FYI: I made cards for the "Family and Friends Matter" and "Checking In"  features. They each require making a change to the recipe, so I thought having dedicated cards would help keep the pipeline clean for QA. I also assigned them to myself and pointed them as 1s since they're technically already done.

**Comment by Stackblocks** [comment]
Updating the initial comment to reflect the slug change from `college-success-high-school` to `preparing-for-college-success` in case anyone else goes here first for that.
