### ISSUE TITLE
[due by end of w.w. sprint] Add Introduction to Behavioral Neuroscience (80%) to Carnival Theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5134]
# Link to content
https://github.com/openstax/osbooks-neuroscience
Slug: neuroscience
Recipe name: neuroscience

Tagging legend: https://docs.google.com/spreadsheets/d/12gEADqgrarSEu2RST21ncngd_P-p8lDN79rd78XP5LI/edit#gid=0

# Design elements in the title

## Color for header and bands
B2: `#0074BC`

### Initial Setup :
- [x] Initial Cookbook/Styles Setup: Working Card: #5296 

### General things:
- [x] Generic things to pull - Documentation #4736 / Working card: #5271
- [x] Table of Contents - Documentation #4730 / Working card: #5272
- [x] Splash image - Documentation #1075 / Working card: #5273
- [x] Figure and table caption/title/number styling - Documentation #1081 / Working card: #5274
- [x] Fonts and Headers - Documentation #4732 / Working card: #5275
- [x] Chapter Outline & Introduction - Documentation #4738 / Working card: #5276
- [x] Learning Objectives - Documentation #1077 / Working card #5277
- [x] Tables (generic) - Documentation #1080 / Working card: #5278
- [ ] NONE right now 🤔 Verify that exercises are able to be pulled in from exercises.openstax.org 

### Feature-like things:
- [x] Meet the Author #5279
- [x] Neuroscience Across Species #5280
- [x] Neuroscience in the Lab #5281
- [x] Developmental Perspective #5282
- [x] Generic boxed feature #5288

### End of Chapter Content
- [x] Section Summary - #5283
- [x] Key Terms ^ covered above
- [x] Reverences ^ covered above
- [x] Multiple Choice ^ covered above
- [x] Fill in the Blank ^ covered above

### End of Book Content
- [x] YES APPENDICES - There isn't content for this now, can we make sure it's supported in the recipe and we can test styling once we get content? (Should follow regular headers though and might be covered by the headers card above)
- [ ] Answer Key - Documentation # 4757 / Working Card # TBD missing assessments
- [x] Index - Documentation #4755 / Working Card #5284
