### ISSUE TITLE
[Upkeep] Inventory the cookbook & styles devcontainer

### ISSUE THREAD

**Issue by Stackblocks** [openstax/cnx-recipes#5150]
## User Story
As a developer I want to know what components are installed in the styles devcontainer[^1], what version they're on, and why they're included so that I can have a clear picture of what's happening in there and suggest additions to add functionality or suggest the removal of components which are no longer used, in disrepair, or no longer play nice with our setup.

## Context
At present the VSCode live share component is either broken or causing difficulties, and with upgrades to Ruby, etc. on the horizon it would be good to take inventory of the devcontainer, tidy it up if that needs doing, and document it somewhere folks who aren't looking at the code can find it.

## Acceptance Criteria
- [ ] A document is created which lists out the contents of the devcontainer, their current version number and a comment on why the component is included in the devcontainer.
- [ ] Ownership of the devcontainer is established (or if it already exists gets plainly stated) in the document so that people know where to go with questions or issues.[^2]
- [ ] Components which are currently out of date are updated or commented with why they are not updated.
- [ ] Components which are broken or no longer used are removed

## Associated Cards

- [x] #5156 
- [x] #5159 
- [x] #5157
- [x] #5158

[^1]: In case "styles devcontainer" isn't the right term: I mean the container that is used to create a common platform for styles work to be developed and tested in.
[^2]: Ownership can be an individual or a team effort, but it should be clarified.

**Comment by kswanson33** [comment]
We will discuss on Monday call and decide what we use/don't use/want to add/want to :fire:

**Comment by wilkus27** [comment]
Document with information about all current components: https://docs.google.com/document/d/1NjzAjUR7hqcMKtuEQ0ZGx44jv2ZmYc8sn6zbwhdVo9Y/edit#heading=h.3ptw3m6h06ds

Here are cards for next steps:
- https://github.com/openstax/cnx-recipes/issues/5159
- https://github.com/openstax/cnx-recipes/issues/5158
- https://github.com/openstax/cnx-recipes/issues/5156
- https://github.com/openstax/cnx-recipes/issues/5157

**Comment by wilkus27** [comment]
@lwtchu It's mostly done. We have never discussed second point - ownership of the devcontainer.

**Comment by wilkus27** [comment]
Devcontainer can be modified by any developer that has an access to repository. There is no need to choose the owner.
