### ISSUE TITLE
[styles framework] add tracking key to styles

### ISSUE THREAD

**Issue by kswanson33** [openstax/cnx-recipes#5179]
Context: https://openstax.slack.com/archives/C022NETP39N/p1687970091974159

User story: As a developer, I want to be more easily able to find which Sass component corresponds to a block of styles in CSS.

Add a unique `_source` value to each Sass component, and when compiled to CSS, this value should appear in each style block as a comment.

AC:

- [ ] A unique source exists on each Sass component
- [ ] There is an easy-to-use method to generate unique sources for future Sass components
- [ ] These sources appear in CSS as comments
- [ ] Test coverage enforces presence of sources & their uniqueness

**Comment by kswanson33** [comment]
currently implementing this using javascript, as that is already installed in the ce-styles project

**Comment by lwtchu** [comment]
Lots of uncertainty - might switch to python. Scheduling for later maybe :eyes:

**Comment by lwtchu** [comment]
Take the idea for this and include in the future styles framework upgrade
