### ISSUE TITLE
Add Polish Marketing to the Cardboard Theme

### ISSUE THREAD

**Issue by wilkus27** [openstax/cnx-recipes#5269]
# Link to content

- https://github.com/openstax/osbooks-pl-marketing/tree/main

# General Notes

Based on the English version: https://github.com/openstax/cnx-recipes/issues/4401.

# Design elements in the title

General things:

- [ ] Table of Contents

Feature-like things:

- [ ] remove Career in marketing https://github.com/openstax/cnx-recipes/issues/4724

End of Chapter Content

- [ ] remove Building Your Personal Brand (class="building-brand") https://github.com/openstax/cnx-recipes/issues/4440
- [ ] remove What Do Marketers Do? (class="marketers-do") https://github.com/openstax/cnx-recipes/issues/4440
- [ ] References
