### ISSUE TITLE
[Due 12/15] Add Lifespan Development (80%) to the Cosmos Theme

### ISSUE THREAD

**Issue by lwtchu** [openstax/cnx-recipes#5298]
# Link to content
- This is a new book.  Please do not work on this until you have talked to me.
- Test content: https://github.com/openstax/osbooks-lifespan-development
- Branch: design-chapter
- Style name: lifespan-development

# General Notes 

## Theme assets folder
- https://drive.google.com/drive/u/0/folders/1r-6jPOZZNRL35fhbSgTn6cT5CiQMRn-2

# Design elements in the title

General things:
- [x] Generic things to pull from other titles - Documentation:  #3173 Working card:  #5310
- [x] Table of Contents - Documentation:  #3154  Working card:  #5311
- [x] Headers - Documentation:  #3164 Working card:  #5312
- [x] Splash image - Documentation:  #3171 Working card:  #5313
- [x] Chapter Outline - Documentation  #3175 Working card:  #5314
- [x] Section Learning Objectives - Documentation  #3175  Working card: #5319
- [x] Introduction -  Documentation  #3191 Working card:  #5320
- [x] Figure & figure title/captions - Documentation  #3183 Working card:  #5321
- [x] Tables - Documentation:  #3185 Working card:  #5322
- [x] Vertically tight tables and header row - #5323

### [Cosmos asset folder for icons.](https://drive.google.com/drive/folders/1r-6jPOZZNRL35fhbSgTn6cT5CiQMRn-2?usp=sharing)
Feature-like things:
- [x] Link to Learning #5324
- [x] What Have You Heard? #5327
- [x] It Depends (yellow box) #5325
- [x] Intersections and Contexts (green box) #5328
- [x] Life Hacks (purple box) #5326

End of Chapter Content 
- [x] Key Terms - big working card here #5330
- [x] Section Summary
- [x] References
- [x] Review Questions - Documentation  
- [x] Check Your Understanding Questions
- [x] Reflection Questions
- [x] Media Questions
- [x] Thought Provokers
- [x] Case Study Questions
 
End of Book Content
- [x] References - #5331 (Slightly different than what we usually do - might need to make new documentation card but asking first if possible - WW asked for both to see possibilities)
- [x] Index  - Documentation:  #3217 Working Card:  #5332
- [x] Glossary Appendix - #5333
- [x] Answer Key Documentation: #3252 / Working Card #5336

# Tagging Legend
https://docs.google.com/spreadsheets/d/1gcDW_NeptLKUE53kT9s5aDfjM1LSdlwdyXNfSzaDmNY/edit#gid=0
