### ISSUE TITLE
Add Information Systems (80%) to the Cardboard Theme

### ISSUE THREAD

**Issue by caylaeagon** [openstax/cnx-recipes#5362]
# Link to content
https://github.com/openstax/osbooks-foundations-of-information-systems
slug: foundations-of-information-systems
style name: information-systems

# Design elements in the title

General things:
- [x] Generic things to pull - Documentation  #2712 / Working card:  #5363
- [x] Table of Contents - Documentation  #1740 / Working card:  #5364
- [x] Splash image - Documentation  #2642 / Working card:  #5365
- [x] Figure and table caption/title/number styling - Documentation  #2643 / Working card:  #5366
- [x] Headers - Documentation  #2644 / Working card:  #5367
- [x] Chapter Outline & Introduction - Documentation  #2655 / Working card:  #5368
- [x] Section number treatment - Documentation  #2710 / Working card:  #5369
- [x] Learning Outcomes - Documentation  #2711 / Working card:  #5370
- [x] Tables - Documentation  #2741 / Working card: # 5371
- [x] Footnotes - Documentation #2773 / Working card: #5374
- [x] Blockquotes - Documentation #2749 / Working card: #5373
- [x] Centered text - Documentation #3654  / Working card: #5372
- [x] Verify that exercises are pulled in from exercises.openstax.org (are there exercises or are there errors)

###  [Cardboard asset folder for icons.](https://drive.google.com/drive/folders/1wsO8nLf7QJj6YnB1pmjPle0hVYwMoyP)

Feature-like things:
- [x] Link to Learning - Documentation #2737 / Working card: #5376
- [x] IS Future Tech - Documentation #2737 / Working card: #5378
- [x] IS Global Connect - Documentation #2737 / Working card: #5379
- [x] IS Ethics - Documentation #2737 / Working card: #5380
- [x] IS Careers - Documentation #2737 / Working card: #5381

End of Chapter Content
- [x] Key Terms - Documentation #2742  / Working card: #5377
- [x] Section Summary  - Documentation #2743 / Working card: #5387
- [x] Assessments: Review Questions Working card: #5382
- [x] Assessments: Check Your Understanding Questions Working card: #5382
- [x] Assessments: Reflection Questions Working card: #5382
- [x] Assessments: Media Questions Working card: #5382

End of Book Content
- [x] YES APPENDICES - please follow regular header stuff
- [x] Answer Key - Documentation #2748 / Working card: #5393
- [x] Index  - Documentation  #2746 / Working card:  #5375

# Tagging Legend
https://docs.google.com/spreadsheets/d/1efAZsE5kMm_-CD_eYgpQyZgf1JFnaQElY38G2OkL6tE/edit#gid=0
