### ISSUE TITLE
Track content decisions and fixes for AW phase 2

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#645]
### Top titled tables books (just need the  `top-titled` class added):
- [x] Astronomy (we did this)
- [ ] Dev math titles (Prealgebra, Elementary Algebra, Intermediate Algebra) - fix in Q1-2019
- [ ] Chemistry; Chemistry Atoms First - fix in Q1-2019 (higher-priority than math)

### Misc table problems
- [ ] Psychology (currently the title is in the caption, we will move it for Baked PDF)

### Books where we will need to move the title from a title row to the title element **for baked PDF**
- [ ] Chemistry 2e; Chemistry Atoms First 2e
- [ ] Dev math titles (Prealgebra, Elementary Algebra, Intermediate Algebra) (? Larissa thinks DevMath already uses the title tag)
- [ ] Astronomy 

### Misc class problems
- [x] astronomy in feature classes have typos - will fix.
