### ISSUE TITLE
Overview and decisions: Implement Page Breaks Library-wide

### ISSUE THREAD

**Issue by helenemccarron** [openstax/cnx-recipes#861]
Design and implement a comprehensive approach to page breaks for Baked PDF

List of items that should *not* break:
- [ ] Table headers
- [ ] Titles
- [ ] Exercises titles

**Comment by openstaxalina** [comment]
@brittany-johnson will park questions at dev roundtable or sometime soon.

**Comment by brittany-johnson** [comment]
**ToDo**
- [ ] Create a list of page break issues from present to 8/17 and group them into categories 
- [ ] Gather all of the page break styles from OER 
- [ ] Create a function or mixin to handle predicted page breaks 
- [ ] Test by comparing before and after mixin on baked pdf styles in different books

Per book/theme imports for page breaks (ex: Book doesn't have an answer key so don't import it)

**Test in:** 
- [ ] Economics 

**Question:** 
- Should page break mixins handle padding?
- What elements do we know that should never break? 
- Are there any elements that we have to explicitly say to break? 

**Page break related issues:** 

**Notes**
Title in note: 
https://github.com/openstax/oer.exports/issues/3786

Subtitle in Note 
https://github.com/openstax/oer.exports/issues/3878

Exampe (Note): 
https://github.com/openstax/oer.exports/issues/2628

**EOC**
EOC Titles: 
https://github.com/openstax/oer.exports/issues/3837
https://github.com/openstax/oer.exports/issues/3426
https://github.com/openstax/oer.exports/issues/3150

**Equations**
https://github.com/openstax/oer.exports/issues/3821

**Footnotes**
https://github.com/openstax/oer.exports/issues/3537

**Tables**
https://github.com/openstax/oer.exports/issues/3302

**Captions (Figures, tables, ect.)**
https://github.com/openstax/oer.exports/issues/3437

**Chapter Outline**
https://github.com/openstax/oer.exports/issues/3057

**Comment by brittweinstein** [comment]
@brittweinstein create 5/7 release and epic and g.g. milestone and put this in there.

**Comment by brittweinstein** [comment]
Do not put any page breaks anywhere for now.

**Comment by openstaxalina** [comment]
We started opening issues with specific page break problems: https://github.com/openstax/cnx-recipes/issues/1462

**Comment by brittweinstein** [comment]
For Devs: Make note of **any** page breaks/extra rules we should consider in this epic.

**Comment by brittany-johnson** [comment]
[Link to page break specs](https://docs.google.com/spreadsheets/d/1vW0EHvn8fZgvTxZIm9xQXsqsnIDcolqwt5rWKtx4JEY/edit#gid=1804222758)

- Brought page break rules from oer.exports that were common in most or all books
- Tested these rules with the first 10 chapters of bio-2e, hs-physics, and physics 
- Made adjustments and additions to page break styles based on findings
- Added page break rules to spec doc linked above 
- Doc reviewed by Larissa and final adjustments were made

**Comment by brittweinstein** [comment]
Please verify that as a result https://app.zenhub.com/workspaces/textbook-developers-5cdc84baee941c07853fbbf2/issues/openstax/cnx-recipes/1462 is no longer an issue.

**Comment by MartaSztuka** [comment]
@brittweinstein It's still an issue.
![Screenshot from 2020-02-18 14-23-32](https://user-images.githubusercontent.com/47241114/74739996-4d8f6980-525a-11ea-9b81-c8b981322b7e.png)

**Comment by brittany-johnson** [comment]
@brittweinstein @MartaSztuka This is expected behavior. I only looked at hs physics, physics, and bio 2e because they were the highest priority last sprint.

**Comment by MartaSztuka** [comment]
@brittweinstein 
College Physics
![Screenshot from 2020-02-19 13-47-31](https://user-images.githubusercontent.com/47241114/74836867-8e51b600-5320-11ea-873a-f189c4c157df.png)
HS Physics
![Screenshot from 2020-02-19 13-24-59](https://user-images.githubusercontent.com/47241114/74834223-4d0ad780-531b-11ea-91b5-eea549fd7471.png)
Biology 2e
![Screenshot from 2020-02-19 14-05-35](https://user-images.githubusercontent.com/47241114/74837047-ec7e9900-5320-11ea-8888-0cb42ff872ef.png)
![Screenshot from 2020-02-19 14-05-25](https://user-images.githubusercontent.com/47241114/74837051-edafc600-5320-11ea-9abc-1729275f46b1.png)
Rest of those books looks ok.

**Comment by MartaSztuka** [comment]
College Physics p.43/44
![Screenshot from 2020-02-20 08-58-14.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/ac84a2d4-a11c-44ee-bbdf-e868ad303acf)

**Comment by brittany-johnson** [comment]
College Physics: 
![Screen Shot 2020-02-24 at 4 32 09 PM](https://user-images.githubusercontent.com/24909007/75197224-5c2ac480-5723-11ea-8c84-1bf410c195ef.png)

![Screen Shot 2020-02-25 at 9 01 12 AM](https://user-images.githubusercontent.com/24909007/75259356-81fcab80-57ad-11ea-9ee2-48f3264dee0c.png)

**Comment by brittany-johnson** [comment]
HS Physics
<img width="1652" alt="Screen Shot 2020-02-25 at 2 00 26 PM" src="https://user-images.githubusercontent.com/24909007/75282845-542c5c80-57d7-11ea-85fb-d148727f658b.png">

**Comment by brittany-johnson** [comment]
Bio 2e
<img width="1652" alt="Screen Shot 2020-02-25 at 3 18 43 PM" src="https://user-images.githubusercontent.com/24909007/75288579-416b5500-57e2-11ea-9ac9-148424c0c88e.png">
<img width="1608" alt="Screen Shot 2020-02-25 at 3 25 55 PM" src="https://user-images.githubusercontent.com/24909007/75289103-39f87b80-57e3-11ea-96fb-601b45f5b161.png">

**Comment by brittany-johnson** [comment]
@MartaSztuka Ready for testing!

**Comment by MartaSztuka** [comment]
Biology 2e - looks ok
![Screenshot from 2020-02-27 15-41-17](https://user-images.githubusercontent.com/47241114/75455105-a0ae9e00-5977-11ea-8b8a-476baf626481.png)
College Physics - partly fixed
![Screenshot from 2020-02-27 16-19-17](https://user-images.githubusercontent.com/47241114/75457795-339e0700-597d-11ea-8b3d-d10da495000c.png)
![Screenshot from 2020-02-27 16-18-44](https://user-images.githubusercontent.com/47241114/75457798-34369d80-597d-11ea-940f-c765f97f3293.png)
HS Physics - still one line in Contents![Screenshot from 2020-02-27 15-42-12](https://user-images.githubusercontent.com/47241114/75457839-46184080-597d-11ea-98d7-59d9818e035e.png)

**Comment by brittany-johnson** [comment]
Decision from PL on 2/27: 
Chapter titles in TOC should be able to break (via @lwtchu ) 

I will create a new PR to update this

**Comment by brittany-johnson** [comment]
@MartaSztuka This is ready for testing again! This is the spreadsheet with page break rules for reference. Let me know if you have any questions: 

https://docs.google.com/spreadsheets/d/1vW0EHvn8fZgvTxZIm9xQXsqsnIDcolqwt5rWKtx4JEY/edit#gid=1804222758

**Comment by MartaSztuka** [comment]
@brittany-johnson According to spreedsheets page breaks looks ok, except for two things i HS Physics:
Index has single letter![Screenshot from 2020-03-06 14-27-28.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/623f0335-f3af-409c-aa3b-56f814a4256d)
Single table row in Appendix![Screenshot from 2020-03-06 14-35-26.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/1f6f5475-f41d-4218-9916-24d1fcc70fbb)
Biology 2e![Screenshot from 2020-03-06 14-16-00.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/fbc9e9d7-d157-44a0-90c5-5b5ff3d06908)
College Physics![Screenshot from 2020-03-06 14-22-02.png](https://images.zenhubusercontent.com/5cb5ec14fec3b63424e0f03c/26a6f3db-6c88-46ff-a7ef-3594b460c9cf)

**Comment by brittany-johnson** [comment]
I think the table should be fine? @lwtchu What do you think? (RE the link to the image)

**Comment by brittweinstein** [comment]
@lwtchu says that this is OK
